### ISSUE TITLE
"Use Cellular Data" turned off is reported incorrectly as reachable

### ISSUE THREAD

**Issue by jwhitehouse** [ashleymills/Reachability.swift#1]
Turning off "Use Cellular Data" specifically for one application, is still reported by the Reachability class as reachable, despite not being able to load data from a remote server.

For example, using a `UIWebView` and having "Use Cellular Data" off does not load a remote URL and falls into the delegate function `didFailLoadWithError`, the code being `NSURLErrorNotConnectedToInternet`. However, the same view controller will report `isReachable()` as true.

This may yet not be able to be resolved without changes from Apple.

**Comment by ashleymills** [comment]
@jwhitehouse It looks like this issue has been resolved. Testing with the sample app with a cellular connection but *use cellular data* set to off in settings gives a status of **Not Reachable**.  Can you please check out the latest version (I was working against the develop branch but master should also work) and feedback here?

Cheers
Ash

**Comment by ashleymills** [comment]
Closing issue as this appears to have been resolved in iOS 9.x
