### ISSUE TITLE
<Error>: SCNetworkReachability fallback status not available, timeout

### ISSUE THREAD

**Issue by j4nos** [ashleymills/Reachability.swift#10]
I am using Reachability class and sometimes it just freeze the whole app at launch, all I can see in device terminal:

`<Error>: SCNetworkReachability fallback status not available, timeout`

and it is logged in every one sec

**Comment by ashleymills** [comment]
Can you give any more info about this issue please:

Does it occur on device or simulator?
What OS version are you running on?
Which device?
How often does it happen?
Are there steps you can take to reproduce it?

Thanks
Ash

**Comment by j4nos** [comment]
Real device, newest iOS, iPhone 5, 1 from 5 case approximately. No it is random. I will test it more.

**Comment by ashleymills** [comment]
Thanks j4nos. 

Does it occur when connected via:

WiFi? 
Cellular?
No connection?

**Comment by j4nos** [comment]
wifi ..

**Comment by ashleymills** [comment]
@j4nos  I've just created a new release (v2.0) that builds for Swift 2.0. Can you please let me know if this is still an issue wh en using the latest release?

Thanks
Ash

**Comment by ashleymills** [comment]
No reply, closing issue
