### ISSUE TITLE
Logic for `isConnectionRequiredOrTransient` looks wrong

### ISSUE THREAD

**Issue by humblehacker** [ashleymills/Reachability.swift#100]
Here's the code:

```swift
private func isConnectionRequiredOrTransient(flags: SCNetworkReachabilityFlags) -> Bool {
        let testcase:SCNetworkReachabilityFlags = [.ConnectionRequired, .TransientConnection]
        return flags.intersect(testcase) == testcase
    }
```

The intersection of `testcase` and `flags` will only be equal to `testcase` if _both_ flags in `testcase` are present in `flags`.  So either the logic of this method is incorrect, or the function name should be changed to `isConnectionRequiredAndTransient`.  I'm not sure which.

**Comment by ashleymills** [comment]
@humblehacker Thanks for raising this issue. I'll update this in the next release (with iOS 10)
