### ISSUE TITLE
 Please, check IPv6

### ISSUE THREAD

**Issue by arpeggi** [ashleymills/Reachability.swift#104]
News for Supporting IPv6-only Networks
https://developer.apple.com/news/?id=05042016a

Please, check IPv6

sockaddr_in -> sockaddr_in6

https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift#L125

**Comment by cezheng** [comment]
There's no need to change sockaddr_in -> sockaddr_in6

To everyone asking for IPv6 support. Take a look at the README of Apple's official version of Reachability: https://developer.apple.com/library/ios/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11

It says 

> IPv6 Support

> Reachability fully supports IPv6.  More specifically, each of the APIs handles IPv6 in the following way:

> **reachabilityForInternetConnection:  This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6.**
