### ISSUE TITLE
Podspec issue -> Cocoapods 1.0.0

### ISSUE THREAD

**Issue by jet-snag** [ashleymills/Reachability.swift#105]
Hi @ashleymills .
As soon as I update pod to 1.0.0, I've got following error.

Could you please fix?

Re-creating CocoaPods due to major version update.
Analyzing dependencies
Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift`, commit `fa90df50c04f5743fbdf643cbe8d10562d75673d`
[!] Unable to find a specification for 'ReachabilitySwift'.

**Comment by brandenr** [comment]
We're stuck on Cocoapods 0.39.0 until this is fixed

**Comment by lockys** [comment]
For someone who accidentally upgrades to Cocoapods 1.0.0 like me and meets this error, 
`pod _0.39.0_ install` to use version 0.39.0 temporarily until the #97 is merged by @ashleymills :cry:

**Comment by ashleymills** [comment]
Spec is Cocoapods 1.x compatible
