### ISSUE TITLE
Add Copyright Notice

### ISSUE THREAD

**Issue by deemadden** [ashleymills/Reachability.swift#111]
Hi Ashley,
I check through all of the open and closed issues, and didn't see this - could you please add a copyright notice?  
Thanks!

**Comment by mitchellporter** [comment]
The license is right here: https://github.com/ashleymills/Reachability.swift/blob/master/LICENSE

**Comment by deemadden** [comment]
Just saw it @mitchellporter thanks.  Closing it.
