### ISSUE TITLE
3.0 Swiftification

### ISSUE THREAD

**Issue by ashleymills** [ashleymills/Reachability.swift#124]
The original Reachability.swift was inspired by Tony Million's Reachability library, which was based on Apple's Objective-C Reachability. As Swift develops, so does Reachability.swift, but it still carries some Objective-C baggage with it. 

Have you looked at the code and thought… "there's a much Swiftier way of achieving that"? If so, please raise a PR (against the iOS10 branch for now). Let's take this code into 2017!! 😄 

Cheers
Ash

**Comment by Dimi70** [comment]
Martin R did post a Swift 2 and Swift 3 reachability code example:
http://stackoverflow.com/questions/25623272/how-to-use-scnetworkreachability-in-swift/25623647#25623647
