### ISSUE TITLE
Xcode 8 beta 6

### ISSUE THREAD

**Issue by simplealina** [ashleymills/Reachability.swift#126]

**Comment by ashleymills** [comment]
Not sure what you're asking here

**Comment by simplealina** [comment]
If you update Xcode 8 with the version released yesterday you will see several changes are needed.

**Comment by perlmunger** [comment]
I can elaborate. Many of the issues can be fixed automatically with Editor | Fix All in Scope (Ctrl+Option+Command+F), however, the unsafe pointer syntax needs some attention and I'm not sure how to satisfy the compiler:

<img width="991" alt="reachability_swift" src="https://cloud.githubusercontent.com/assets/17556/17723005/c1f9f096-63f3-11e6-8ee9-716e02504682.png">

**Comment by robertoschwald** [comment]
We fixed it for Alamofire yesterday. Please check.

https://github.com/elm4ward/Alamofire/commit/7f74c6dcdc249c7d9cf2f742441c91ad9f2f8981#diff-f2ea78e6e262089f9f5c5b13cd9121db

**Comment by ashleymills** [comment]
Thanks for your comments - I just pushed an update

Ash
