### ISSUE TITLE
Module name is not consistent between Cocoapods and Carthage

### ISSUE THREAD

**Issue by amarcadet** [ashleymills/Reachability.swift#128]
I know this is a small issue because there's little chance that people use both installation methods but the module name is `ReachabilitySwift` with cocoapods (same as podspec name) and `Reachability` with carthage (as defined in target).

This could be solved by adding `s.module_name = 'Reachability'` to the `.podspec` file.
It's a breaking change so I understand that you would consider this issue not relevant for now.

It would also help switchers from both side to migrate their code.

Thanks for your time.

**Comment by MontakOleg** [comment]
Hi,
I'm working on library which uses Reachability and can be installed via cocoapods and carthage. So different module names is problem for me.
It would be nice to follow @amarcadet suggestion.

**Comment by m-ylmz** [comment]
I saw the same issue in another project, and they found a workaround for it, see [here](https://github.com/cbpowell/MarqueeLabel/issues/181).

**Comment by hamchapman** [comment]
It's now `import Reachability` for both Cocoapods and Carthage
