### ISSUE TITLE
Just for clarification

### ISSUE THREAD

**Issue by acegreen** [ashleymills/Reachability.swift#129]
Hello, is it so when we opt to go with the closure method, are we still notified of changes to reachability? Or do we also need to addObserver and check within our selector?

In other words if I 
- setup my reachability 
- include both my .whenReachable {} and .whenUnreachable {}. 
- and then startNotifier()

Will this just handle the initial check after initiation only or will it do that and also call the appropriate callback in case of reachability change?

**Comment by ashleymills** [comment]
The notification is still sent whether or not `.whenReachable/Unreachable` closure properties are set.
