### ISSUE TITLE
reachability.startNotifier() causes a crash in swift3(xCode8-beta6)

### ISSUE THREAD

**Issue by taku99** [ashleymills/Reachability.swift#130]
I implemented reachability.swift from iOS10 branch into my swift3 project on xCode8-beta6 and got an error that I couldn't resolve.
I noticed that the app crashes when  _reachability.startNotifier_ is called to post a notification. 
```
let reachability = Reachability()!
NSNotificationCenter.defaultCenter().addObserver(self, selector: "reachabilityChanged:",name: ReachabilityChangedNotification,object: reachability)
    do{
      try reachability.startNotifier()
    }catch{
      print("could not start reachability notifier")
    }
```
The app crashes here
![screen shot 2016-08-25 at 2 55 16 am](https://cloud.githubusercontent.com/assets/15806467/17947278/02eb6d8e-6a87-11e6-9f12-cb28f16fbb10.png)

And this is what I can see in the log.

> *** NSForwarding: warning: object 0x10d939668 of class 'WebClient' does not implement methodSignatureForSelector: -- trouble ahead Unrecognized selector +[WebClient reachabilityChanged:]

Please let me know how I can resolve this problem.

**Comment by podilivinay** [comment]
#130.. I am also getting the same issue. Is anybody having solution for this?
