### ISSUE TITLE
Carthage update dont work

### ISSUE THREAD

**Issue by dunqi** [ashleymills/Reachability.swift#136]
cannot capture 'reachabilityFlags' before it is declared
error: value of type 'SCNetworkReachabilityFlags' has no member 'intersection'
error: type 'SCNetworkReachabilityFlags' has no member 'isDirect'
use of unresolved identifier 'isConnectionRequiredFlagSet'

If i use "carthage update Reachability.swift --platform ios" on v.3 branch (master)

**Comment by ashleymills** [comment]
Is your project set to build with Swift 3.0?

**Comment by dunqi** [comment]
No - I'm still using XCode 7. After one day - Carthage update works fine - no Idea why - nothing changed since yesterday - But I can work on now.
