### ISSUE TITLE
ReachabilitySwift 3.0 doesn't update with Cocoapods

### ISSUE THREAD

**Issue by davilinho** [ashleymills/Reachability.swift#138]
I've updated XCode 8.0 with Swift 3, and I can't update ReachabilitySwift 3.0

> [!] Unable to satisfy the following requirements:

- `ReachabilitySwift (~> 3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ReachabilitySwift (~> 3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by zirinisp** [comment]
I have the same problem.

**Comment by ashleymills** [comment]
I think it's due to the tags having a `v` in front of them - I'm checking for a solution.
If you're building for Swift 3, you should just be able to remove the `(~3)` for now

**Comment by ashleymills** [comment]
Ah - my fault! Didn't `push trunk` - on it now

**Comment by davilinho** [comment]
Ok! I'm waiting! Thanks!

**Comment by davilinho** [comment]
When will be available to download with cocoapods?

**Comment by zirinisp** [comment]
Is there any way I can use a branch on cocoapods, so we can use Swift 3 now?

**Comment by davilinho** [comment]
> Is there any way I can use a branch on cocoapods, so we can use Swift 3 now?

How can I use this branch?

**Comment by ashleymills** [comment]
If you want to use the Swift 3 code now (while I resolve the problem) you can include the file directly in your project.

Just download and drop in this file… https://github.com/ashleymills/Reachability.swift/blob/master/Reachability/Reachability.swift

**Comment by davilinho** [comment]
Ok, thanks a lot

**Comment by zirinisp** [comment]
Thank you. Keep us posted once it is ready so we can revert back to cocoapods.

**Comment by abunur** [comment]
I noticed you had a commit recently, just FYI this still doesn't resolve this issue, i.e. if you include , '~> 3' in your pod file you get the same error.  Removing it resolves that.

**Comment by davilinho** [comment]
> https://github.com/ashleymills/Reachability.swift/blob/master/Reachability/Reachability.swift
> Does not work in Xcode 8 GM
> 

I agree... I have problems too

**Comment by davilinho** [comment]
I've tried this:

`pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git', :tag => 'v3'`

And It seems than works for me... It's correctly?

**Comment by mime29** [comment]
Please add a  
s.pod_target_xcconfig = {
                 'SWIFT_VERSION' => '3.0'
              }
to the podspec file.
Otherwise, there will be an error after each pod install.

**Comment by ashleymills** [comment]
@davilinho @mime29 Thanks guys - I added a `.swift-version` file (per https://github.com/CocoaPods/CocoaPods/pull/5841) , which seems to have resolved the issue, so you now should be able to specify
```
pod 'ReachabilitySwift', '~> 3'
```
