### ISSUE TITLE
Error : Invalid bitcode version (Producer: '800.0.38.0_0' Reader: '703.0.31_0')

### ISSUE THREAD

**Issue by monica18p** [ashleymills/Reachability.swift#139]
I am using xcode 7.3, with swift 2.1.
Recently I changed pod specification to following as you have updated the pod compatibility to swift 2.3 and above: 
`pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift', :commit => '217ba79579efbfebd66691666b782ecd04fe5f5b'`

I am using [https://buddybuild.com/](url) for uploading and archiving my app.
On archiving i am getting these two errors:
1. error: Invalid bitcode version (Producer: '800.0.38.0_0' Reader: '703.0.31_0')
2. clang: error: linker command failed with exit code 1 (use -v to see invocation)

Then i removed the pod and manually added Reachability.swift file in my project. Still i am getting the same error. Can you please suggest the workaround for this.
FYI:- Enabled bitcode : Yes

Thanks.

**Comment by mkeefe** [comment]
@monica18p - Just came across this same problem. Try setting **Enable Bitcode = NO** in Build Settings of your app target.

**Comment by kirtiparghi** [comment]
I am using xcode 7.3, with swift 2.1.

I am getting these two errors:
error: Invalid bitcode version (Producer: '800.0.42.1_0' Reader: '703.0.29_0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried to disable bitcode in my main project target. But it's not working.

**Comment by sukeshj** [comment]
+1

**Comment by shoaibahmedqureshi** [comment]
I am also receiving this same error (Producer: '800.0.42.1_0' Reader: '703.0.29_0') with cocoapods in library 'AltHanekeSwift', '0.10.10' and enable Bitcode = NO in Build Settings of app target  does not work.

**Comment by raviatri** [comment]
@kirtiparghi @shoaibahmedqureshi any luck with this issue? i am facing same problem!!
