### ISSUE TITLE
Cannot update to v2.4 for swift 2.3

### ISSUE THREAD

**Issue by Huy-Vu** [ashleymills/Reachability.swift#140]
I try to update to v2.4 and got this 
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ReachabilitySwift (= 2.4)` required by `Podfile`
```

**Comment by DiegoRenau** [comment]
pod 'ReachabilitySwift', '~> 2.3'

**Comment by gabriellanata** [comment]
Does not work for me either:

```
[!] Unable to satisfy the following requirements:

- `ReachabilitySwift (~> 3.0)` required by `Podfile`
```

**Comment by ashleymills** [comment]
Swift 3 should now be working as expected using
```
pod 'ReachabilitySwift', '~> 3'
```

I need to make some updates for Swift 2.3 hopefully later today, but for now please try
```
pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git', :branch-> 'swift-2.3', :tag => 'v2.4'
```

**Comment by DiegoRenau** [comment]
pod 'ReachabilitySwift', '~> 2.3'
is working for me in Swift 2.3 with pod --version 1.0.1.
Then: let reachability: Reachability = try! Reachability(hostname: "api.xxxxx.com")

**Comment by ashleymills** [comment]
Swift 2.3 should now be supported. Use
```
pod 'ReachabilitySwift', '~> 2.4'
```
in your podfile
