### ISSUE TITLE
Swift 3.0 compatible

### ISSUE THREAD

**Issue by Piyush08** [ashleymills/Reachability.swift#143]
Hi,
When I try to include this library via cocoa pods, it gives me warning for swift 3.0 as follow image.
I added via "pod 'ReachabilitySwift', '~> 3'"
It gives me lots of error if I convert it to swift 3.0

Please help me to resolve this.

![screen shot 2016-09-18 at 8 03 20 pm](https://cloud.githubusercontent.com/assets/7929845/18616536/4cf56c6a-7ddb-11e6-946d-3a278b65da2d.png)

**Comment by ebelinski** [comment]
The version of ReachabilitySwift you are using needs to have the same Swift version as your Xcode project. If you do that, you won't need to convert ReachabilitySwift yourself. If your project is Swift 3.0, you need ReachabilitySwift version 4, if it's Swift 2.3, you need version 2.4. This is all in the [readme](https://github.com/ashleymills/Reachability.swift).

**Comment by mime29** [comment]
With the latest version I think it's fine though. They added the podspec flag to set the Swift version on the pod.
If you still have the problem you can still do this in your podfile

# Changes build active architecture only
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' #Temporary change for migration
    end
  end
end

**Comment by sirvon** [comment]
@ebelinski hey, did you really mean "3" here ~>

>  If your project is Swift 3.0, you need ReachabilitySwift version 4,

**Comment by ashleymills** [comment]
Just to confirm:
Swift 2.3 ~> 2.4 (sorry about that, but there were already 2.3.x versions)
Swift 3 ~> 3
