### ISSUE TITLE
Cocoapods dependency cause build failed on pod lib lint - Swift 3.0

### ISSUE THREAD

**Issue by barbaracsilveira** [ashleymills/Reachability.swift#146]
We are migrating our library for Swift 3.0 and use the Reachability as dependence on our podspec. 

Cocoapods version: 1.1.0.rc.2
Xcode: Version 8.0

We performed this test on a sample library:
'Pod lib create Test'

Add the Reachability as dependence on Podspec:
`s.dependency 'ReachabilitySwift', '~> 3'`

And we run the terminal command line:
`pod lib lint --verbose --no-clean --allow-warnings`

We get the error below:

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /var/folders/yg/dlxwsn292j108t5qtlmgbtfh0000gn/T/CocoaPods/Lint/Pods/ReachabilitySwift/Reachability/Reachability.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
 -> Teste (0.1.0)
    - WARN  | summary: The summary is not meaningful.
    - WARN  | url: There was a problem validating the URL https://github.com/<GITHUB_USERNAME>/Teste.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:92:5: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:92:16: error: consecutive declarations on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:94:5: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:94:16: error: consecutive declarations on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:102:5: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:102:16: error: consecutive declarations on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:103:5: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:103:16: error: consecutive declarations on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:105:5: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:105:16: error: consecutive declarations on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:146:52: error: boolean condition requires 'where' to separate it from variable binding
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:228:1: error: expressions are not allowed at the top level
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:228:12: error: consecutive statements on a line must be separated by ';'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:239:28: error: expected member name following '.'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:239:28: error: 'default' label can only appear inside a 'switch' statement
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:244:31: error: braced block of statements is an unused closure
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:298:1: error: expected declaration
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:33:32: error: use of undeclared type 'Error'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:40:46: error: type 'NSNotification' has no member 'Name'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:42:92: error: use of undeclared type 'UnsafeMutableRawPointer'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:105:47: error: use of unresolved identifier 'DispatchQueue'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:33:13: error: type 'ReachabilityError' does not conform to protocol 'RawRepresentable'
    - NOTE  | [iOS] xcodebuild:  Swift.RawRepresentable:9:20: note: protocol requires nested type 'RawValue'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:228:1: error: use of unresolved identifier 'fileprivate'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:48:5: error: use of unresolved identifier 'DispatchQueue'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:122:36: error: use of unresolved identifier 'MemoryLayout'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:125:65: error: extraneous argument label 'to:' in call
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:149:24: error: use of unresolved identifier 'UnsafeMutableRawPointer'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:152:37: error: thrown expression type 'ReachabilityError' does not conform to 'ErrorType'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:157:37: error: thrown expression type 'ReachabilityError' does not conform to 'ErrorType'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:179:15: error: use of unresolved identifier 'isReachableFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:181:12: error: use of unresolved identifier 'isConnectionRequiredAndTransientFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:186:16: error: use of unresolved identifier 'isOnWWANFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:197:37: error: use of unresolved identifier 'isReachableFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:197:59: error: use of unresolved identifier 'isOnWWANFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:203:15: error: use of unresolved identifier 'isReachableFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:209:17: error: use of unresolved identifier 'isOnWWANFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:214:38: error: use of unresolved identifier 'isOnWWANFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:215:17: error: use of unresolved identifier 'isReachableFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:216:17: error: use of unresolved identifier 'isConnectionRequiredFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:217:17: error: use of unresolved identifier 'isTransientConnectionFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:218:17: error: use of unresolved identifier 'isInterventionRequiredFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:219:17: error: use of unresolved identifier 'isConnectionOnTrafficFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:220:17: error: use of unresolved identifier 'isConnectionOnDemandFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:221:17: error: use of unresolved identifier 'isLocalAddressFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:222:17: error: use of unresolved identifier 'isDirectFlagSet'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:232:21: error: use of local variable 'reachabilityFlags' before its declaration
    - NOTE  | xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:282:9: note: 'reachabilityFlags' declared here
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:244:31: error: unable to infer closure return type in current context
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:252:44: error: type 'SCNetworkReachabilityFlags' has no member 'reachable'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:255:44: error: type 'SCNetworkReachabilityFlags' has no member 'connectionRequired'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:258:44: error: type 'SCNetworkReachabilityFlags' has no member 'interventionRequired'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:261:44: error: type 'SCNetworkReachabilityFlags' has no member 'connectionOnTraffic'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:264:44: error: type 'SCNetworkReachabilityFlags' has no member 'connectionOnDemand'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:267:17: error: value of type 'SCNetworkReachabilityFlags' has no member 'intersection'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:270:44: error: type 'SCNetworkReachabilityFlags' has no member 'transientConnection'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:273:44: error: type 'SCNetworkReachabilityFlags' has no member 'isLocalAddress'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:276:44: error: type 'SCNetworkReachabilityFlags' has no member 'isDirect'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:279:16: error: value of type 'SCNetworkReachabilityFlags' has no member 'intersection'
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:287:48: error: extraneous argument label 'to:' in call
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:279:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:276:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:273:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:270:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:267:17: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:264:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:261:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:258:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:255:16: error: cannot capture 'reachabilityFlags' before it is declared
    - ERROR | [iOS] xcodebuild:  ReachabilitySwift/Reachability/Reachability.swift:252:16: error: cannot capture 'reachabilityFlags' before it is declared

Pods workspace available at `/var/folders/yg/dlxwsn292j108t5qtlmgbtfh0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

[!] Teste did not pass validation, due to 69 errors.

**Comment by pxrne** [comment]
create a .swift-version file in your repo and in it write a single line: 3.0
