### ISSUE TITLE
Type 'Reachability' has no member 'reachabilityForInternetConnection'

### ISSUE THREAD

**Issue by sreejithsn** [ashleymills/Reachability.swift#148]
after upgrading pod reachability 3, i am getting above error

**Comment by ashleymills** [comment]
See readme for Swift 3 breaking changes

**Comment by RosemolJ** [comment]
Got the same issue.. Below code doesn't support Swift 3. Any solution ?

        ```
do {
            reachability = try Reachability.reachabilityForInternetConnection()
        } catch {
            print("Unable to create Reachability")
            return
        }

```

**Comment by r-a-o** [comment]
RTFM: https://github.com/ashleymills/Reachability.swift#swift-3-breaking-changes

```
       do {
            reachability = try Reachability.reachabilityForInternetConnection()
        } catch {
            print("Unable to create Reachability")
            return
        }
```

is now simply,

`        let reachability = Reachability()`

**Comment by matteocollina** [comment]
`reachability.isReachable` 
works for me for ReachabilitySwift
_Swift version 4.0.3_
