### ISSUE TITLE
reachability.startNotifier() causes a crash in swift3(xCode8)

### ISSUE THREAD

**Issue by sreejithsn** [ashleymills/Reachability.swift#149]
reachability.startNotifier() causes a crash in swift3(xCode8)

**Comment by archiejudd** [comment]
I'm having the same problem...

**Comment by ashleymills** [comment]
Away from computer for a few days, please try stackoverflow.com in the meantime

**Comment by ashleymills** [comment]
https://github.com/ashleymills/Reachability.swift/wiki/Raising-an-issue
