### ISSUE TITLE
ReachabilitySwift 2.4 cant compile it on xcode 8 even with legacy option YES

### ISSUE THREAD

**Issue by tabish0027** [ashleymills/Reachability.swift#159]
i am trying to run the 2.4 release on xcode 8.0 but it says the following message 
Module file was created by an older version of the compiler; rebuild 'ReachabilitySwift' and try again

**Comment by ashleymills** [comment]
Sounds like you're using Swift 3 for your app. Version 2.4 is Swift 2.3 (confusing, sorry!)

You need v3 (you can specify a version in Carthage or CocoaPods)
