### ISSUE TITLE
Am getting this error on ` let reachability = Reachability()`

### ISSUE THREAD

**Issue by cosmo1234** [ashleymills/Reachability.swift#160]
`Cannot invoke initializer for type 'Reachability' with no arguments`

**Comment by ashleymills** [comment]
What version of Xcode / Swift are you using?

**Comment by plspalding** [comment]
Hi, I am having the same issue. When using `let reachability = Reachability()`! I am getting the same error `Cannot invoke initializer for type 'Reachability' with no arguments`

I am using Xcode 8 and swift 2.2.3.

**Comment by ashleymills** [comment]
I assume you mean you're using Swift 2.3 (not 2.2.3). In which case, you should use the old syntax:
```
let reachability = try! Reachability.reachabilityForInternetConnection()
```

**Comment by plspalding** [comment]
doh! Not sure how I missed that in the  > Swift 3 breaking changes

Cheers for quick response.
