### ISSUE TITLE
Reachability causing didUpdateLocations not getting called

### ISSUE THREAD

**Issue by MahmoudTarek** [ashleymills/Reachability.swift#165]
Hello, whenever I use Reachability, didUpdateLocations won't get called for some reason, I'm not sure why or how Reachability can have influence on map services. Any help would be appreciated.

**Comment by ashleymills** [comment]
I'm not sure why either.

**Comment by MahmoudTarek** [comment]
Okay, I haven't made any major changes that's why I haven't mentioned my ways, anyway:
- I have installed Reachability using Cocoapods 
`pod 'ReachabilitySwift', '~> 3'`
- I'm using Xcode 8, Swift 3.
- I have ViewController X having the following methods:
`override func viewDidLoad() {
        super.viewDidLoad()
        setupReachability(nil, useClosures: true)
        startNotifier()
}

func setupReachability(_ hostName: String?, useClosures: Bool) {
        hostNameLabel.text = hostName != nil ? hostName : "No host name"
        
        print("--- set up with host name: \(hostNameLabel.text!)")

        let reachability = hostName == nil ? Reachability() : Reachability(hostname: hostName!)
        self.reachability = reachability
        
        if useClosures {
            reachability?.whenReachable = { reachability in
                DispatchQueue.main.async {
                    self.updateLabelColourWhenReachable(reachability)
                }
            }
            reachability?.whenUnreachable = { reachability in
                DispatchQueue.main.async {
                    self.updateLabelColourWhenNotReachable(reachability)
                }
            }
        } else {
            NotificationCenter.default.addObserver(self, selector: #selector(ViewController.reachabilityChanged(_:)), name: ReachabilityChangedNotification, object: reachability)
        }
    }
    
    func startNotifier() {
        print("--- start notifier")
        do {
            try reachability?.startNotifier()
        } catch {
            networkStatus.textColor = .red
            networkStatus.text = "Unable to start\nnotifier"
            return
        }
    }
    
    func stopNotifier() {
        print("--- stop notifier")
        reachability?.stopNotifier()
        NotificationCenter.default.removeObserver(self, name: ReachabilityChangedNotification, object: nil)
        reachability = nil
    }

func reachabilityChanged(_ note: Notification) {
        let reachability = note.object as! Reachability
        
        if reachability.isReachable {
            updateLabelColourWhenReachable(reachability)
        } else {
            updateLabelColourWhenNotReachable(reachability)
        }
       stopNotifier()
    }

`

- There's a segue from X opens ViewController Y which has the following methods:
`
override func viewDidLoad() {
        super.viewDidLoad()      
        locationManager = CLLocationManager()
        self.locationManager.requestAlwaysAuthorization()
        self.locationManager.requestWhenInUseAuthorization()
        if CLLocationManager.locationServicesEnabled() {
            self.locationManager.delegate = self
            self.locationManager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
            self.locationManager.startUpdatingLocation()
        }
}

func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
    let locValue:CLLocationCoordinate2D = manager.location!.coordinate
    self.longitude = locValue.longitude
    self.latitude = locValue.latitude
    print("Location has been updated")
    locationManager.stopUpdatingLocation()
}`

didUpdateLocations in Y won't get called after startNotifier in X.

Sorry for the confusion, thanks in advance.

**Comment by MahmoudTarek** [comment]
Sorry for the code mess, can't get it configured correctly. My apologize.

**Comment by ashleymills** [comment]
@MahmoudTarek Thanks for the update. You need a strong reference to your reachability variable, so declare it at class level. 
See the example in the README, issues #144, #93, #85

**Comment by MahmoudTarek** [comment]
Great, it worked fine. Thank you so much.
