### ISSUE TITLE
Is this cope with 'IPv6'？

### ISSUE THREAD

**Issue by tomokitakahashi** [ashleymills/Reachability.swift#168]
I develop app by Swift3.0 .
But , my app was rejected .

**Comment by leedowthwaite** [comment]
I have the same question - just had an app rejected for IPv6 noncompliance - no details unfortunately. Can you confirm whether this lib works with IPv6?

**Comment by dcortes22** [comment]
Same for me, anybody confirm if this is working on IPv6?

**Comment by Laptopmini** [comment]
I need to run this test, but if anyone is interested in testing their own app for this requirement:

https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16

**Comment by Abhishekg219** [comment]
Do you guys have any answer for this ?

**Comment by leedowthwaite** [comment]
FYI, I removed this Pod from the app and resubmitted, and Apple approved it. I know it's not conclusive, but it *suggests* maybe this library is not IPv6-compliant.

**Comment by ashleymills** [comment]
I've submitted updates to a couple of apps several times that contain this Reachability library, without any problem.

**Comment by Abhishekg219** [comment]
@ashleymills @leedowthwaite  
Hey guys, seems like whenever Apple got a crash when the app is in review they mentioned that the app was tested under IPv6 network...
Mine issue was fixed and app got approved also.

Thanks a lot everyone

**Comment by ashleymills** [comment]
@Abhishekg219 Thanks… as far as we are aware, there is no current problem with the library regarding IPv6 - Apple seem to include the IPV6 warning when they reject an app, whether or not that was the cause.

**Comment by tomokitakahashi** [comment]
Thank you , everyone.  I solved this problem !

**Comment by springhand** [comment]
I have also been told ipv6 problem, how do you solve?

**Comment by ashleymills** [comment]
Please see the note above. Your app crashed when Apple was testing it. It was tested on an IPv6 network. You need to fix whatever's causing your app to crash

**Comment by RajanFernandez** [comment]
FYI, I have to agree with @leedowthwaite here. An app of mine was getting rejected for IPv6 only networking failures. After running my app on a IPv6 network I found that the Apple review team was right. You can find details on how to do this in Apple documentation: Networking Overview - Test for IPv6 DNS64/NAT64 Compatibility Regularly.

I also found that the latest pod version was crashing here:
```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_pthread.dylib       	0x1d28a91e pthread_mutex_lock + 10
1   SystemConfiguration           	0x1de21080 SCNetworkReachabilitySetCallback + 42
```
I have also removed this pod from my project for these reasons, but hopefully this information will allow someone clever to fix the issue :)
