### ISSUE TITLE
It won't compile on WatchOS 3. Will it support WatchOS 3?

### ISSUE THREAD

**Issue by allenlinli** [ashleymills/Reachability.swift#169]
This library doesn't support WatchOS now. Will it be able to support in the future?

> [!] The platform of the target `Watch-Proto Watch App` (watchOS 3.0) is not compatible with `ReachabilitySwift (3)`, which does not support `watchos`.

I install the library on CocoaPods, with version pod 'ReachabilitySwift', '~> 3'.

**Comment by hamchapman** [comment]
The `System Configuration` framework isn't supported on watchOS and so it's unlikely that it'll be easy to add support for watchOS

**Comment by allenlinli** [comment]
I see. Thank you.
