### ISSUE TITLE
Swift 3 breaking changes : reachabilityForLocalWiFi

### ISSUE THREAD

**Issue by tchukuchuk** [ashleymills/Reachability.swift#170]
Hi,

I used Reachability.reachabilityForLocalWiFi with the 2.3.3 release, but now it doesn't seem available with the 3. How can I check now the reachability for local wifi ?

Regards,

Julien

**Comment by nick3389** [comment]
I have the same problem too. Is there any advice?

**Comment by nick3389** [comment]
I wrote an extension based on the swift23 branch of reachabilityForLocalWiFi for now

**Comment by Laptopmini** [comment]
It got renamed to `isReachableViaWiFi`.

So for example, in `AppDelegate`:
```
reachability.whenReachable = { reachability in
    DispatchQueue.main.async {
        if reachability.isReachableViaWiFi {
            print("Apple Device reachable via WiFi.")
        } else {
            print("Apple Device reachable via Cellular.")
        }
    }
}
```
