### ISSUE TITLE
Remove sign Identity from framework project

### ISSUE THREAD

**Issue by amosavian** [ashleymills/Reachability.swift#171]
Hi,
please remove signing identity by updating project to Xcode 8 recommended settings

**Comment by reversepanda** [comment]
Yes, please update the framework project. The current status will break Carthage builds. 

Sincerely,
Kaweh

**Comment by reversepanda** [comment]
Small correction: latest Carthage doesn't have problems with the project. I was using an out-of-date version of Carthage. Sorry for the confusion.

**Comment by amosavian** [comment]
I don't use Carthage, I added manually
Tnx
