### ISSUE TITLE
Does this library work with iOS 10.0+?

### ISSUE THREAD

**Issue by Laptopmini** [ashleymills/Reachability.swift#172]
In the README, it says this library works with iOS 8.0 to 10.0. Is this up to date?

If yes, what is the behavior of this library on iOS 10.1.1 for example? App crashes or safely fails?

Thank you for any input

**Comment by andrewkouri** [comment]
I'm also looking for this answer -- but for 10.2 :)

**Comment by Laptopmini** [comment]
Just finished migrating to Swift 3, tested on physical device running 10.2 working perfectly. 

However, watch out for #168.

**Comment by apouche** [comment]
I'm having a weird issue starting with iOS 10.2 as well. The behavior is fine only the first time. The `reachability?.whenUnreachable` is properly called once when connection is lost.

However after that successful call is made all subsequent connections lost/gain are never accessed ever again. So the call to `reachability?.whenReachable ` never occurs once connection has been lost.

This is only happening on iOS 10.2 (maybe 10.x but didn't try). 

You guys are having the same issue ?
