### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.0.2:

### ISSUE THREAD

**Issue by alexrmacleod** [ashleymills/Reachability.swift#173]
Getting the below error after using Carthage update to import Reachability.swift. 

"Module compiled with Swift 2.3 cannot be imported in Swift 3.0.2:"

Any idea on how I can use Carthage to import Reachability.swift and get it to work with Swift 3.0.2? Can't use podfile my project is too far along and will probably explode if I do. 

After running carthage update this is what the terminal put out 
Alexs-MacBook-Air:Tipped-18 New SDK alex$ carthage update
*** Fetching Reachability.swift
*** Fetching CryptoSwift
*** Checking out CryptoSwift at "0.6.7"
*** Checking out Reachability.swift at "v2.4"
*** xcodebuild output can be found in /var/folders/69/dpcnlc_n0517_5258j4sb73c0000gn/T/carthage-xcodebuild.ilvfqQ.log

**Comment by ashleymills** [comment]
You'll need to point to v3 for Swift 3 compatibility. Something like…

github "ashleymills/Reachability.swift ~> `v3`
