### ISSUE TITLE
Detect no data transfer either via WWAN or Cellular Data?

### ISSUE THREAD

**Issue by dinaraja** [ashleymills/Reachability.swift#174]
Is there any possibility to identify Internet is connected via WWAN or Cellular Data, but no data is transferring?

If I start the tethering in any device and connected, it says internet is reachable via WWAN, even though tethering device is not connected to internet at all. Is there any way to detect this? 

Please provide any example if possible.

**Comment by ashleymills** [comment]
This isn't supported at present. You might want to try logging the `description`, and checking the different flag states when tethered / untethered.
