### ISSUE TITLE
Wi-fi connection with no internet

### ISSUE THREAD

**Issue by anismansuri** [ashleymills/Reachability.swift#175]
I connect my phone to router. but router is not connected to internet. How can i get that state that wifi has active internet connection or not?

**Comment by ashleymills** [comment]
If you create your Reachability object with `init(hostname: String)`, and use, say, `google.com` as the hostname it will fail if you can't connect to google.com

**Comment by anismansuri** [comment]
let reachability = try  Reachability(hostname: "https://www.google.com")
its not working.

**Comment by ashleymills** [comment]
OK

**Comment by anismansuri** [comment]
can u provide some solution?

**Comment by ashleymills** [comment]
You're joking, right?

**Comment by anismansuri** [comment]
no man.I'm serious.

**Comment by anismansuri** [comment]
if i check this isReachableViaWiFi(). it'll return true.

**Comment by emreoktem** [comment]
Probably this is duplicate of #115 

There may be missing information above but there's really a problem with init(hostname: String) metod...

**Comment by ashleymills** [comment]
@anismansuri thanks for the extra info. Please read the [guidelines for contributing](https://github.com/ashleymills/Reachability.swift/blob/master/CONTRIBUTING.md) before submitting an issue in future. 
@emreoktem thanks - if you have a solution, I'll be happy to take a pull request!

**Comment by emreoktem** [comment]
@ashleymills this problem is a big headache for our app at the moment and I'm working on a solution which is actually a quick fix and not very elegant. I will let you know.

**Comment by anismansuri** [comment]
@emreoktem let me know if solve this issue.

**Comment by emouawad** [comment]
Any Progress on the issue? i can confirm the bug.

**Comment by Yozine** [comment]
Installed via CocoaPods, swift 3 branch.

initialised: 
private let hostReachability = Reachability(hostname: "http://www.google.com") 

usage:
`       hostReachability?.whenUnreachable = {[weak self] reachability in
            self?.networkIsConnected = false //when set to true, works as expected
        }
        
        hostReachability?.whenReachable = {[weak self] reachability in
            self?.networkIsConnected = true //when set to false, works as expected
        }
        
        do {
           // try reachability?.startNotifier()
            try hostReachability?.startNotifier()
        } catch {
            //fail silently
            debugPrint("failed to set up reachability")
        }`

The function seems to return whenReachable = true when it shouldn't be and whenUnreachable = false when it is actually true. The expected behaviour is that I should set networkIsConnected to false when the state is unReachable and true for whenReachable. Works as expected when I switch the booleans around.

**Comment by Y2JChamp** [comment]
hello, i have the same identical issue but i don't see any solution in here. Why is the issue closed?

**Comment by komalguptatii** [comment]
I am facing the same issue too when wifi is connected but there is no internet connection and still its return true for wifi connectivity.
Any solutions?
