### ISSUE TITLE
what is 'reachabilityForLocalWiFi' in the 3.0 version?

### ISSUE THREAD

**Issue by Daij-Djan** [ashleymills/Reachability.swift#176]
what is 'reachabilityForLocalWiFi' in the 3.0 version?

thanks
dominik

**Comment by christophercotton** [comment]
Looks like it was removed as per Apple's guidelines: https://developer.apple.com/library/content/samplecode/Reachability/Listings/ReadMe_md.html

> Removal of reachabilityForLocalWiFi
> ============
> Older versions of this sample included the method reachabilityForLocalWiFi. As originally designed, this method allowed apps using Bonjour to check the status of "local only" Wi-Fi (Wi-Fi without a connection to the larger internet) to determine whether or not they should advertise or browse. 
>  
> However, the additional peer-to-peer APIs that have since been added to iOS and OS X have rendered it largely obsolete.  Because of the narrow use case for this API and the large potential for misuse, reachabilityForLocalWiFi has been removed from Reachability.
>  
> Apps that have a specific requirement can use reachabilityWithAddress to monitor IN_LINKLOCALNETNUM (that is, 169.254.0.0).  
>  
> Note: ONLY apps that have a specific requirement should be monitoring IN_LINKLOCALNETNUM.  For the overwhelming majority of apps, monitoring this address is unnecessary and potentially harmful.

In the new one, you can just use the default constructor:

`let reachability = Reachability()`


If you can, go ahead and mark this as closed.

**Comment by ashleymills** [comment]
@christophercotton Thanks for the update - this is correct
