### ISSUE TITLE
Carthage failing to detect v3 release

### ISSUE THREAD

**Issue by classic-chris** [ashleymills/Reachability.swift#178]
The numbering scheme is broken for the version 3 release of the Reachability framework. It should be "v3.0" not simply "v3".

Carthage will fail to resolve the version 3 release until the number scheme is corrected. Please update the release tag ASAP! :-)

**Comment by ashleymills** [comment]
This framework has been downloaded getting on for 2 million times, and is in 10s of thousands of apps - and this is the first time I've heard of this problem. Are you _sure_ it's an issue?

**Comment by classic-chris** [comment]
Hi Ashley,

Yes, I'm afraid I'm sure.

My Cartfile contains:
`github "ashleymills/Reachability.swift"`

I perform: `carthage update` as usual.

Instead of resolving to the most recent version Carthage checks out v2.4, the last version with a valid release tag. My Cartfile.resolved confirms this:
`github "ashleymills/Reachability.swift" "v2.4"`

If I explicitly specify the v3 in the Cartfile like so: `github "ashleymills/Reachability.swift" == "v3"` carthage update fails with 

> Parse error: unexpected trailing characters in line: github "ashleymills/Reachability.swift" == "v3"

From my own experience the problem is the lack of a minor number on the release tag. v3.0 instead of v3 should sort this out and would be consistent with your existing numbering scheme.

**Comment by ashleymills** [comment]
How about `github "ashleymills/Reachability.swift" "v3"`?

**Comment by classic-chris** [comment]
That sorted it, thank you! :-) 

I believe this still constitutes a break with your previous configurations, however. Normally a Carthage user would expect to receive the most up-to-date release of a project if they do not specify a version in their Cartfile and perform a `carthage update`. I realise this behaviour will be reasserted when you release v3.1 but it still seems like an anomaly to me.
