### ISSUE TITLE
Cannot inherit from non-open class reachbility ousisde of it's defining module'

### ISSUE THREAD

**Issue by ShadyGhalab** [ashleymills/Reachability.swift#179]
I want to inherit reachbility class outside of the defining module so i think it should the class be Open instead of public.

**Comment by ashleymills** [comment]
Subclass-ability is a non-goal for this project. However, as it's open source you can go ahead and fork and amend / subclass to your heart's content! 😄

**Comment by ShadyGhalab** [comment]
Thank you :)

**Comment by slhodson969** [comment]
![why-just-why-meme-43291](https://cloud.githubusercontent.com/assets/2744879/23159090/cacaa9b4-f821-11e6-8538-279bfba375e0.jpg)

Without this it's not easy to mock the class for unit testing purposes. At least as far as I can see.

**Comment by ashleymills** [comment]
if you want to mock it, maybe what you need is `ReachabilityProtocol`, that Reachability and your mock object conform to.

**Comment by slhodson969** [comment]
Thats what I ended up doing, creating my own `ReachabilityProtocol` and then added a wrapper around `Reachability` that complies to the protocol. If this class was open though there wouldn't be a need for that.
