### ISSUE TITLE
Problem with a cellular data?

### ISSUE THREAD

**Issue by SebastianKumor** [ashleymills/Reachability.swift#180]
One of my test user from US(distributed trough test flight) said that reachability displayed that there is no connection even though she was on a LTE. Anyone encountered anything like this before? I never had a problem with reachability using 3g or 4g.

**Comment by benTipple** [comment]
Also having this issue.

**Comment by SebastianKumor** [comment]
I figured out that the problem was caused on ios 10 device because in cellular data settings for my app was for some reason disabled.

**Comment by ashleymills** [comment]
@SebastianKumor thanks for following up

**Comment by jstheoriginal** [comment]
Thanks for this...I never even thought of this being something to check for. I've had people encounter an issue but they say they have Internet (and emailed me fine via my app's feedback mechanism).

Cheers.

**Comment by thejeraldo** [comment]
Was also having an issue with specific user on LTE. Cannot detect if there is internet connection just after downloading our app from the App Store and also other apps in his phone works fine.
