### ISSUE TITLE
Does this class will work for IPV6 ?

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [ashleymills/Reachability.swift#183]
My app is rejected three times , does this class work for IPV6 Reachability test?

**Comment by indrajitsinh** [comment]
@ZetrixWeb-iOS  take a look at this https://developer.apple.com/news/?id=05042016a

**Comment by ashleymills** [comment]
Yes. Your app is crashing. Apple test on an IPV6 network. The 2 may not be related. You need to fix the crashes
