### ISSUE TITLE
Adding github "ashleymills/Reachability.swift" to Cartfile installs Swift 2.3 version

### ISSUE THREAD

**Issue by valeriyvan** [ashleymills/Reachability.swift#184]
Adding `github "ashleymills/Reachability.swift"` to Cartfile installs Swift 2.3 version, not Swift 3 as you might expect.

**Comment by ashleymills** [comment]
https://github.com/ashleymills/Reachability.swift/blob/master/README.md#important

**Comment by valeriyvan** [comment]
There's no example what to do with Carthage if you need Swift 3 version.
I've proposed update for README.md #185  to make this clear.
