### ISSUE TITLE
carthage update --platform iOS --no-use-binaries produces error

### ISSUE THREAD

**Issue by valeriyvan** [ashleymills/Reachability.swift#186]
Updating dependencies with `carthage update --platform iOS --no-use-binaries` produces error:

```
*** Skipped building Reachability.swift due to the error:
Dependency "Reachability.swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ashleymills/Reachability.swift/issues/new
```

But `carthage update` works just fine.

**Comment by hamchapman** [comment]
This is an old issue so things might have changed since then but it definitely shouldn't be an issue now:

<img width="675" alt="screen shot 2018-04-07 at 22 05 14" src="https://user-images.githubusercontent.com/2475150/38460345-cac73e2e-3aaf-11e8-83c1-626ffb53eff3.png">
