### ISSUE TITLE
Use of unresolved identifier "Reachability" 

### ISSUE THREAD

**Issue by samuelbeek** [ashleymills/Reachability.swift#19]
When I Install Reachability using CocoaPods, I get this error message when using it in any context
        
       Use of unresolved identifier "Reachability"

**Comment by baldurh** [comment]
Same problem here

**Comment by samuelbeek** [comment]
@baldurh thanks! that did it for me!

**Comment by AndreiBoariu** [comment]
Thanks a lot... Perfect notice... It should be added in git hub details, when install via cocoa pods.
Thanks
