### ISSUE TITLE
Drawback of single instance approach?

### ISSUE THREAD

**Issue by danielsaidi** [ashleymills/Reachability.swift#190]
Hi there,

I recently took over management of an app that uses Reachability in several service classes and view controllers. This makes coupling to the Reachability pod (however good) quite extensive, with almost all view controllers and connected classes requiring this pod in order to function.

Instead of using this approach, are there any obvious drawbacks with having a single reachability instance in AppDelegate and use that to detect connectivity changes and notify all other classes with a custom system notification?

All the best

Daniel

**Comment by ashleymills** [comment]
@danielsaidi,

that sounds like a perfectly reasonable approach. Each Reachability instance has one `whenReachable` and .whenUnreachable` closure, so if you're using a single instance in the AppDelegate, either you'll have to forward the state change somehow, or you can listen for `reachabilityChanged` notification in any view controller… https://github.com/ashleymills/Reachability.swift/blob/master/README.md#example---notifications

**Comment by danielsaidi** [comment]
Perfect, thanks for the quick reply!
