### ISSUE TITLE
reachability only notifies once and then stops notifying on iPad (iOS 10.0.2)

### ISSUE THREAD

**Issue by account-archived-270316** [ashleymills/Reachability.swift#196]
I have followed the example in the readme using NotificationCenter. But reachability only notifies once the first time it is added to NotificationCenter as an observer. And after that turning on/off wifi doesn't trigger any notification.

iPad is running iOS 10.0.2.

**Comment by ashleymills** [comment]
Can you please install the sample app on you iPad, and let me know if that is working correctly.

**Comment by account-archived-270316** [comment]
@ashleymills sure. I will try it out after updating my iPad to 10.2

**Comment by account-archived-270316** [comment]
hmmm working pretty good, if `setupReachability("invalidhost", useClosures: true)` is never called.

**Comment by account-archived-270316** [comment]
Alright, problem found. Readme has not been updated for the newer version of swift which adopts to the new convention of using `Notification` instead of `NSNotification`.
