### ISSUE TITLE
Connection status will be delayed five seconds

### ISSUE THREAD

**Issue by mujan5427** [ashleymills/Reachability.swift#2]
Hi Ashley, thank you for providing such a good tool

The use of some questions to ask you

I found that switching from wifi to no connection, it will delay for about 5 seconds

Will return "No Connection"

Within five seconds, the connection status has been returned "WiFi"

Cellular will not be the case, is this normal?

**Comment by ashleymills** [comment]
Hi @mujan5427 

Is this a problem on an actual device, or in the simulator?

**Comment by ashleymills** [comment]
I'm guessing this is due to the block / notifications being fired on a background queue. The latest version fires them on the main queue. See also the develop branch for a version a beta version that supports Swift 2.0 - this also works with no delays.
