### ISSUE TITLE
How to check if the internet is reachable from inside a button

### ISSUE THREAD

**Issue by HasanAlyazidi** [ashleymills/Reachability.swift#201]
Thank you for your contributions to the open source world.

- What version of Reachability.Swift am I using?
        v3

I would like to **check if the internet is reachable from inside a button** (block UI) so i can send data to the server or show an alert in case of the internet is not reachable.

I could do so previously like this:

```
         // check internet reachability
          do {
            reachability = try Reachability.reachabilityForInternetConnection()

            if let reachability = reachability {
                dispatch_async(dispatch_get_main_queue()) {
                    
                    if reachability.isReachable() {
                        // send data to the server
                    } else {
                        // alert: no internet
                    }

                }
            }

        } catch {
            print("Unable to create Reachability")
        }
```

Thank you in advance

**Comment by kuyazee** [comment]
I do something like this

        var hasInternet: Bool {
            if let reachability = Reachability() {
                if reachability.currentReachabilityString == "No Connection" {
                    return false
                } else {
                    return true
                }
            } else {
                return false
            }
        }

        @IBOutlet func someButtonClicked(sender: Any) {
            guard hasInternet else {
                return // do nothing cause there is no internet
            }

            // do stuff here
        }

**Comment by ashleymills** [comment]
Rather than checking `currentReachabilityString == "No Connection"` you should use `currentReachabilityStatus == . notReachable`

**Comment by HasanAlyazidi** [comment]
@kuyazee @ashleymills Thank you very much
