### ISSUE TITLE
Carthage not installing latest version if we doesn't mention version number in cart file

### ISSUE THREAD

**Issue by vidhyasri2106** [ashleymills/Reachability.swift#204]
I have multiple libraries installed in my Xcode project and i didn't mention any version number in it so that i can keep all the frameworks updated. When i try to install Reachability without giving any version, it is installing only 2.0 and that doesn't support my swift version. I believe the recent reachability version is 3.0. Can you please look into this?

**Comment by isunilapps** [comment]
I too came across with this kind of scenario.. to resolve this 
1. I have removed the existing podlock, workspace file along with pods folder
2. uninstalled the cocoa pods "sudo gem uninstall cocoapods" and reinstalled

**Comment by gregpardo** [comment]
They are updating the library for swift 4 it looks like. I did this.

github "ashleymills/Reachability.swift" "v3"
