### ISSUE TITLE
Reachability is not Swift 2.0 compliant.

### ISSUE THREAD

**Issue by UncleRic** [ashleymills/Reachability.swift#21]
Unable to compile/build Reachability using Xcode IDE version 7+/Swift 2.0+.

**Comment by ashleymills** [comment]
Hi, 

Check out the develop branch for a version that compiles under Swift 2. If you're using CocoaPods it's v2.0-beta1

Ash

**Comment by UncleRic** [comment]
I updated my Podfile and re-installed.  Got the following errors during build:

**Comment by ashleymills** [comment]
Can you post the errors?
Cheers
Ash

**Comment by UncleRic** [comment]
> On Jun 15, 2015, at 2:35 PM, Ashley Mills <notifications@github.com> wrote:
> 
> Can you post the errors?
> Cheers
> Ash
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ashleymills/Reachability.swift/issues/21#issuecomment-112218249>.
> 

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name ReachabilitySwift -Onone -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/Ric/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -update-code -I /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods -F /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods -parse-as-library -c -j1 /Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/ReachabilitySwift/Reachability.swift -output-file-map /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/Pods-ReachabilitySwift-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftmodule -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/ReachabilitySwift-generated-files.hmap -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/ReachabilitySwift-own-target-headers.hmap -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/ReachabilitySwift-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/ReachabilitySwift-project-headers.hmap -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/include -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Private -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Private/ReachabilitySwift -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/Bolts -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/FBSDKCoreKit -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/FBSDKLoginKit -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/FBSDKLoginKit/FBSDKLoginKit -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/FBSDKShareKit -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/Parse -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/ParseFacebookUtilsV4 -Xcc -I/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods/Headers/Public/ReachabilitySwift -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/DerivedSources/x86_64 -Xcc -I/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/Ric/Workarea/Bliss\ (DevelopRic)/Pods

<unknown>:0: error: no such file or directory: '/Users/Ric/Workarea/Bliss (DevelopRic)/Pods/ReachabilitySwift/Reachability.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

Ditto /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Headers/ReachabilitySwift-Swift.h /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift-Swift.h
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/ditto -rsrc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift-Swift.h /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Headers/ReachabilitySwift-Swift.h

ditto: can't get real path for source '/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift-Swift.h'
Command /usr/bin/ditto failed with exit code 1

Ditto /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Modules/ReachabilitySwift.swiftmodule/x86_64.swiftmodule /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftmodule
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/ditto -rsrc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftmodule /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Modules/ReachabilitySwift.swiftmodule/x86_64.swiftmodule

ditto: can't get real path for source '/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftmodule'
Command /usr/bin/ditto failed with exit code 1

Ditto /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Modules/ReachabilitySwift.swiftmodule/x86_64.swiftdoc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftdoc
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/ditto -rsrc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftdoc /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/Modules/ReachabilitySwift.swiftmodule/x86_64.swiftdoc

ditto: can't get real path for source '/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftdoc'
Command /usr/bin/ditto failed with exit code 1

Ld /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/ReachabilitySwift normal x86_64
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods -F/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods -filelist /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.LinkFileList -install_name @rpath/ReachabilitySwift.framework/ReachabilitySwift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -framework SystemConfiguration -ObjC -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift.swiftmodule -framework Foundation -framework SystemConfiguration -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/ReachabilitySwift_dependency_info.dat -o /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/ReachabilitySwift

ld: file not found: /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Intermediates/Pods.build/Debug-iphonesimulator/Pods-ReachabilitySwift.build/Objects-normal/x86_64/Reachability.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

GenerateDSYMFile /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework.dSYM /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/ReachabilitySwift
    cd "/Users/Ric/Workarea/Bliss (DevelopRic)/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/ReachabilitySwift -o /Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework.dSYM

error: cannot parse the debug map for "/Users/Ric/Library/Developer/Xcode/DerivedData/Bliss2-cfsnsfhdoqhwejbbgqkdsosrhpuc/Build/Intermediates/SwiftMigration/Bliss2/Products/Debug-iphonesimulator/Pods/ReachabilitySwift.framework/ReachabilitySwift": No such file or directory

**Comment by ashleymills** [comment]
Thanks. What have you tried yourself to resolve this issue? Have done a clean build? Have you tried adding Reachability.Swift without using CocoaPods? Any other info you can give me?

**Comment by UncleRic** [comment]
I haven’t tried the raw route.
I’ve scaled back from Swift 2.0 due to additional complications with other sources.

I’ll retry later… as Swift 2.0 becomes more common.
Ric.

**Comment by petershaw** [comment]
I add the beta tag to the Podfile

```
    pod 'ReachabilitySwift' 'v2.0-beta1'
```

but got the following error:
[!] Unable to find a specification for `ReachabilitySwiftv2.0-beta1`

**Comment by vishaltelangre** [comment]
@petershaw: It should be

`pod 'ReachabilitySwift', '~> 2.0-beta1'`

**Comment by deemadden** [comment]
Any plans to turn this into a branch, or will it just become a fix on master at some point?  We're using our own hacked version that we made 2.0 compatibile.  It would be nice to include it as a proper pod.

**Comment by vishaltelangre** [comment]
Absolutely.

**Comment by ashleymills** [comment]
Once Swift 2.0 is live, I'll merge the develop branch back into master

Ash

**Comment by mkral** [comment]
Any updates on this? I've tried it on Xcode 7 (official release) but I'm getting an error saying:

Binary Operator '!=' cannot be applied to operands of type 'Bool' and 'Int'

**Comment by mkral** [comment]
changing the '0' to 'false' in the errors seems to work.

**Comment by ashleymills** [comment]
Make sure you're using the developer branch and the latest Xcode 7 release

**Comment by mkral** [comment]
sorry, I thought I was. This fixed it.

**Comment by mkral** [comment]
Any idea when this will be merge into master?

**Comment by almazini** [comment]
Also interested when code will be updated into 2.0

**Comment by AaoIi** [comment]
This is giving an error : Binary Operator '!=' cannot be applied to operands of type 'Bool' and 'Int'

  if SCNetworkReachabilitySetCallback(reachabilityRef!, callback, &context) != 0 {
            if SCNetworkReachabilitySetDispatchQueue(reachabilityRef!, reachabilitySerialQueue) != 0 {
                notifierRunning = true
                return true
            }
        }

and 
            if gotFlags != 0 {
                return test(flags)
            }

by changing it to true or false is crashing the whole app, please release a stable version :(

**Comment by ashleymills** [comment]
Develop branch has been merged into master and created a 2.0 release. Please try again

Cheers
Ash

**Comment by AaoIi** [comment]
@ashleymills , thank you very much it works very well, all bugs solved :)
