### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by srinathp90** [ashleymills/Reachability.swift#211]
My podfile has pod 'ReachabilitySwift', :branch => 'develop' as mentioned in the document.
When try to install it i got an error:
**[!] Unknown external source parameters for `ReachabilitySwift`: `{:branch=>"develop"}`**

**Comment by EquaI1ty** [comment]
Same error

**Comment by TheEffekted** [comment]
Same

**Comment by 2mittens** [comment]
Hi guys! The correct way of installing the develop branch is:
`pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git', :branch => 'develop'`
