### ISSUE TITLE
Spelling error (cosmetic only)

### ISSUE THREAD

**Issue by rspreen** [ashleymills/Reachability.swift#22]
line 36:   public type alias NetworkUneachable = ...

I think you mean "Unreachable" (note the 'r')

Not a big problem, but a bit disconcerting to have it so prominent...

**Comment by damonjones** [comment]
I sent a pull request for this a while back: https://github.com/ashleymills/Reachability.swift/pull/15

**Comment by rspreen** [comment]
Oops - I should have seen that, my bad.  Thanks!
