### ISSUE TITLE
Framework includes invalid content when compiled with Xcode 9 Beta 5

### ISSUE THREAD

**Issue by lvandal** [ashleymills/Reachability.swift#220]
The compiled framework includes a Frameworks folder and libswiftRemoteMirror.dylib, which is not allowed by iTunes Connect.

Compiled with Xcode 8.3.3:

<img width="412" alt="screen shot 2017-08-10 at 12 00 00 pm" src="https://user-images.githubusercontent.com/157723/29179875-eac33ab0-7dc3-11e7-9be6-a6b70247dc1e.png">

Compiled with Xcode 9 beta 5

<img width="411" alt="screen shot 2017-08-10 at 12 00 52 pm" src="https://user-images.githubusercontent.com/157723/29179883-f3019a28-7dc3-11e7-80f4-687217bcd135.png">

This causes issues when uploading a binary to iTunes Connect:

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'My.app/Frameworks/Reachability.framework/libswiftRemoteMirror.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

**Comment by jlerner** [comment]
Deleting `libswiftRemoteMirror.dylib` as well as the `Frameworks` directory (which contains a bunch of `.dylib` files) seems to fix the iTunes Connect validation issue without actually breaking anything in Reachability.
