### ISSUE TITLE
Unable to target v3 using carthage

### ISSUE THREAD

**Issue by grantism** [ashleymills/Reachability.swift#227]
After the `v4.0-beta2` release, I am unable to specifically use the `v3` release.
After playing around with my cartfile, it appears the issue is with the versioning of Reachability.swift.

This is the line in my cartfile: 
`github "ashleymills/Reachability.swift" == 3.0.0`.

However, running `carthage update` my cartfile.resolved file looks like this:
`github "ashleymills/Reachability.swift" "v4.0-beta2"`.

This then leads to the reachability project not building in Xcode 8.3.3, with the following error:
```
*** Building scheme "Reachability" in Reachability.xcodeproj
Build Failed
        Task failed with exit code 65:
        /usr/bin/xcrun xcodebuild -project /Workspaces/ios/Carthage/Checkouts/Reachability.swift/Reachability.xcodeproj -scheme Reachability -configuration Release -derivedDataPath /Users/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/Reachability.swift/v4.0-beta2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Workspaces/ios/Carthage/Checkouts/Reachability.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/z7/whc3fjp55850rd_tvy161v6m0000gn/T/carthage-xcodebuild.8mYYP1.log
```

It is possible to specifically target the commit for 3.0 (a17b2882db4803aaea08d7eb1c894304d744be64), but I feel this is not ideal.

**Comment by ashleymills** [comment]
The line in your cartfile is formatted incorrectly. Use…
`github "ashleymills/Reachability.swift" "v3"`
