### ISSUE TITLE
Carthage compilation crash

### ISSUE THREAD

**Issue by ManuRodriguezSebastian** [ashleymills/Reachability.swift#231]
Hi, im used Reachability with Carthage and im using this frameworks : 
```
github "Alamofire/Alamofire" ~> 4.5
github "SwiftyJSON/SwiftyJSON"
github "marketplacer/keychain-swift" ~> 8.0
github "realm/realm-cocoa"
github "ashleymills/Reachability.swift" "v3"
```

If I compile with this configuration, Carthage crash... but if I compile whitout Reachability and then compile after with Reachability, it works. Why? Any solution?

**Comment by ashleymills** [comment]
See #232
