### ISSUE TITLE
`v3` is not a legal semantic versioning tag for Carthage

### ISSUE THREAD

**Issue by antonys1** [ashleymills/Reachability.swift#232]
Can you update the `v3` tag to `v3.0` please? See Carthage issue for details https://github.com/Carthage/Carthage/issues/2171

**Comment by z4r** [comment]
This request is extended to `v4` -> `v4.0`

**Comment by ashleymills** [comment]
@antonys1 Done - can you please check it's now working as expected?
@z4r Noted!

Cheers
Ash

**Comment by z4r** [comment]
`Cartfile` now:

...
`github "ashleymills/Reachability.swift"`
...

Carthage output updating

`*** Checking out Reachability.swift at "v3.0"`

Good job

**Comment by k4ety** [comment]
I don't know what you changed but at around this same time I am now getting this error when trying to install using cocoaPods:

warning: Could not find remote branch v3 to clone.
fatal: Remote branch v3 not found in upstream origin

**Comment by taiheng** [comment]
Podspec is still looking for the old v3 tag, for now this will fix it:

**Comment by hamchapman** [comment]
Closing as fixed 👍
