### ISSUE TITLE
Does it can be used in an Objective-C project?

### ISSUE THREAD

**Issue by ivanstang** [ashleymills/Reachability.swift#233]
Does it can be used in an Objective-C project?
Is there any guide of Objective-C usage?

**Comment by ashleymills** [comment]
Objective-C compatibility isn’t a goal for this project

Cheers
Ash

Ashley Mills
T: +44 7976 363 943 
E: ashleymills@mac.com 
W: http://joylordsystems.com

**Comment by ashleymills** [comment]
If you need Reachability for Objective C, you should use Apple's code [here](https://developer.apple.com/library/content/samplecode/Reachability/Introduction/Intro.html)

**Comment by ivanstang** [comment]
Thanks！

发自我的 iPhone
