### ISSUE TITLE
Value of type 'Reachability' has no member 'connection'

### ISSUE THREAD

**Issue by rurom** [ashleymills/Reachability.swift#236]
Hello! 
I setuped ReachabilitySwift through Cocoapods, but can't find solution for this issue:
**Value of type 'Reachability' has no member 'connection'**

` if reachability.connection == .wifi {
                print("Reachable via WiFi")
                self.customFbLoginSaveUserIntoFIB()
            } else {
                print("Reachable via Cellular")
                self.customFbLoginSaveUserIntoFIB()
            }
        }`
 
Can you please help me solve this issue?
Thanks.

**Comment by juliooa** [comment]
how do you resolve this?  I got the same problem

**Comment by rurom** [comment]
@juliooa 
It seems like an issue with library or Cocoapods (i don't know the real source of this problem).
So i refused Cocoapods, and just made it manually using only ashleymills Reachability.swift file.
Here is simple example which I used  https://github.com/rurom/EzInternetReachability
Note, the name of class was changed from Reachability to InternetReachability.

**Comment by juliooa** [comment]
@rurom thanks! Finally I made the same as you. It seams it was taking the obj-c class :/ don't know why. Using the .swift file directly is better. Thanks!

**Comment by cbielich** [comment]
Life saver! Worked for me as well just removed Reachability with pod and added the file manually
