### ISSUE TITLE
Reachability did not detect 4G Network connection

### ISSUE THREAD

**Issue by pycoder-pjh** [ashleymills/Reachability.swift#238]
I am using reachability.swift in my ios app development. it is working for 3G, wifi but doesn't work for checking 4G Connection status. If any solution, help me please.. Thanks

**Comment by ashleymills** [comment]
Reachability treats all cellular connections the same. Did you have the same problem running the sample app?

**Comment by pycoder-pjh** [comment]
Thanks Ashley Mills for replying.  yes i have the same problem on running
my app.

Thanks & Regards
Jagadeeswaraiah.P

On Sep 28, 2017 2:59 PM, "Ashley Mills" <notifications@github.com> wrote:

Reachability treats all cellular connections the same. Did you have the
same problem running the sample app?

> On 28 Sep 2017, at 07:00, pycoder-pjh <notifications@github.com> wrote:
>
> I am using reachability.swift in my ios app development. it is working
for 3G, wifi but doesn't work for checking 4G Connection status. If any
solution, help me please.. Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ashleymills/Reachability.swift/issues/238#issuecomment-332781675>,
or mute the thread
