### ISSUE TITLE
Ambiguous use of 'reachabilityChanged' after pod update

### ISSUE THREAD

**Issue by FattGuy** [ashleymills/Reachability.swift#242]
I have updated the pod just hours ago and can't get the ReachabilitySwift build.

Here is the screenshot.
<img width="1081" alt="screen shot 2017-10-10 at 5 09 56 pm" src="https://user-images.githubusercontent.com/11469948/31413222-e2fd096a-addd-11e7-8a51-28a0af57bb41.png">

**Comment by ink-spot** [comment]
I have the same issue because another library I use declares the same `.reachabilityChanged` notification, but I can't figure the syntax (or if it's even possible) to namespace the Reachability notification.

**Comment by VeloxIT** [comment]
just use it like that : Notification.Name("reachabilityChanged")
