### ISSUE TITLE
framework not found Reachability / linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by veeralbhateja** [ashleymills/Reachability.swift#248]
Ld /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Products/Debug-iphonesimulator/OpenEarsSampleAppSwift.app/OpenEarsSampleAppSwift normal x86_64
    cd /Users/veeralbhateja/Documents/GitHub/cherrypickprice-sw/OpenEarsSampleAppSwift
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.1.sdk -L/Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Products/Debug-iphonesimulator -F/Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Products/Debug-iphonesimulator -F/Users/veeralbhateja/Documents/GitHub/cherrypickprice-sw/OpenEarsSampleAppSwift/../Framework -F/Users/veeralbhateja/Documents/GitHub/cherrypickprice-sw/OpenEarsSampleAppSwift -filelist /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Intermediates.noindex/OpenEarsSampleAppSwift.build/Debug-iphonesimulator/OpenEarsSampleAppSwift.build/Objects-normal/x86_64/OpenEarsSampleAppSwift.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Intermediates.noindex/OpenEarsSampleAppSwift.build/Debug-iphonesimulator/OpenEarsSampleAppSwift.build/Objects-normal/x86_64/OpenEarsSampleAppSwift_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Intermediates.noindex/OpenEarsSampleAppSwift.build/Debug-iphonesimulator/OpenEarsSampleAppSwift.build/Objects-normal/x86_64/OpenEarsSampleAppSwift.swiftmodule -lc++ -liconv -lz -framework AVFoundation -framework Accelerate -framework AssetsLibrary -framework AudioToolbox -framework CoreMedia -framework MicroBlink -framework Reachability -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Intermediates.noindex/OpenEarsSampleAppSwift.build/Debug-iphonesimulator/OpenEarsSampleAppSwift.build/OpenEarsSampleAppSwift.app.xcent -framework SystemConfiguration -framework UIKit -framework CoreGraphics -framework Foundation -lsqlite3.0 -framework MicroBlink -framework CoreMedia -framework AudioToolbox -framework AVFoundation -framework Accelerate -liconv -lz -lc++ -framework Slt -framework OpenEars -framework Pods_OpenEarsSampleAppSwift -Xlinker -dependency_info -Xlinker /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Intermediates.noindex/OpenEarsSampleAppSwift.build/Debug-iphonesimulator/OpenEarsSa

mpleAppSwift.build/Objects-normal/x86_64/OpenEarsSampleAppSwift_dependency_info.dat -o /Users/veeralbhateja/Library/Developer/Xcode/DerivedData/OpenEarsSampleAppSwift-dnkewgekjwisfufqooufocwtsrrk/Build/Products/Debug-iphonesimulator/OpenEarsSampleAppSwift.app/OpenEarsSampleAppSwift

ld: framework not found Reachability
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="792" alt="screen shot 2017-10-21 at 8 52 12 am" src="https://user-images.githubusercontent.com/19327129/31847665-54951326-b63d-11e7-8205-42e902996687.png">

**Comment by veeralbhateja** [comment]
I installed it using Cocoapods and Manually as well. I am using Xcode Version 9.1 beta.

Cocoapods is giving the error as shown in screenshot above.

**Comment by mariusbologa** [comment]
Hi. I have encountered the same issue. The problem is that the framework name was changed since the version 4.0, as it says on the site. So first you should check out this information. Moreover I had to delete the framework from pod file and from Targets->Build Settings-> Other Linker Flags. Then I reinstalled the pods.

**Comment by hamchapman** [comment]
Closing as stale - feel free to update with more info of your setup if the problem persists.

**Comment by muxtorovinomjon0227** [comment]
For me it worked!

Xcode-->Runner-->Build Setting-->Search(OTHER_LDFLAGS)-->Other Linker Flags  Clear all
