### ISSUE TITLE
Just some usage instruction typos

### ISSUE THREAD

**Issue by atraczyk** [ashleymills/Reachability.swift#250]
1. Step 4 in the Carthage instructions references `ReachabilitySwift.framework`, which I think should be `Reachability.framework`.

2. Step 5 in the Carthage instructions references `$(SRCROOT)/Carthage/Build/iOS/ReachabilitySwiift.framework`, which I think should be `$(SRCROOT)/Carthage/Build/iOS/Reachability.framework`.

**Comment by hamchapman** [comment]
Fixed in master 👍
