### ISSUE TITLE
Using pod of Reachability getting error

### ISSUE THREAD

**Issue by waleedbutt** [ashleymills/Reachability.swift#27]
Hi 
I'm using Reachability class using cocoapods but when I add following line in my Podfile 

pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'

and run pod update command in terminal. the pod successfully added in my project but when I used 
import Reachability

in my controller Xcode give me error like that image (https://cloudup.com/cltJbfDwO3K). I'm using Xcode 6.4 and CocoaPods 0.38
Please give solution of that asap.
Thanks in advance

**Comment by cheneveld** [comment]
import ReachabilitySwift

**Comment by cheneveld** [comment]
@ashleymills maybe update readme?

**Comment by waleedbutt** [comment]
@cheneveld Thanks for update me. I used Reachability class using pods and also use you recommended line of code (i.e. import ReachabilitySwift) in my project and now its working fine. Thanks alot.
