### ISSUE TITLE
EXC_BAD_ACCESS in startNotifier

### ISSUE THREAD

**Issue by hermannkuschke** [ashleymills/Reachability.swift#278]
Hi!

First of all, thank you for this project.

Second, I have a weird issue that I am not able to resolve. I am getting an "EXC_BAD_ACCESS" run time error in the startNotifier function at the following line:

`if(SCNetworkReachabilitySetCallback(self.reachabilityRef, TMReachabilityCallback, &context))`

I've attached an image of the property values at the point of the crash (if that could be of any help).

![screen shot 2018-02-17 at 9 45 35 am](https://user-images.githubusercontent.com/13273739/36339147-71d1bbfa-13c7-11e8-9ad9-e1dd304b3cdb.png)

And here is my setup code:

```
lazy private var networkListener: Reachability? = {
       return Reachability()
    }()
```

```
self.networkListener?.reachableBlock = { [weak self] reachability in
                dLog(message: "internet is reachable")
                guard let strongSelf = self, let reachability = reachability else {
                    self?.reachable.value = false
                    self?.reachableViaWifi.value = false
                    self?.reachableViaCellular.value = false
                    return
                }
                strongSelf.reachable.value = true
                if reachability.isReachableViaWiFi() {
                    dLog(message: "internet is reachable via wifi")
                    strongSelf.reachableViaWifi.value = true
                    strongSelf.reachableViaCellular.value = false
                } else {
                    dLog(message: "internet is reachable via cellular network")
                    strongSelf.reachableViaCellular.value = true
                    strongSelf.reachableViaWifi.value = false
                }
            }
            
            self.networkListener?.unreachableBlock = { [weak self] _ in
                dLog(message: "internet is not reachable")
                self?.reachable.value = false
                self?.reachableViaWifi.value = false
                self?.reachableViaCellular.value = false
            }
            
            self.networkListener?.startNotifier()
```

 I was wondering if you've updated the example code recently as it doesn't look like it. The reason I say so is that it seems that the startNotifier call doesn't need to be in a try catch block anymore but the example still has it in that block. I know I'm guessing here, but that made me assume you might not have updated the example in order to reflect needed changes. Apologies if I'm wrong. I'm just trying to make some educated guesses as to what is going wrong on my end.

Your help is very much appreciated!

Regards,

Hermann Kuschke

**Comment by hermannkuschke** [comment]
Hi, folks! My apologies for involving anyone who reads this in an unrelated issue. I included "pod Reachability" instead of "pod ReachabilitySwift" in my pod file, so I wasn't even working with Ash's code! I can assure you it was an honest mistake though :)

**Comment by BrandonShega** [comment]
I just ran into this myself, I thought by

> If you're adding Reachability.swift using CocoaPods, note that the framework name has changed from ReachabilitySwift to Reachability (for consistency with Carthage)

that the pod name changed but it looks like just the module name changed.
