### ISSUE TITLE
Unable to access Reachability/Develop via Podfile

### ISSUE THREAD

**Issue by UncleRic** [ashleymills/Reachability.swift#28]
$~/workarea/Bliss (DevelopRic):pod install
Analyzing dependencies

CocoaPods 0.38.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

Here's my Podfile:

pod 'Parse'      
use_frameworks!
# pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
# Using Develop Branch for Xcode 7/Swift 2.0:
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift/tree/develop' 
...   
...
--------------------------------------------------------------------------
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift/tree/develop`

[!] Error installing ReachabilitySwift
[!] /usr/local/bin/git clone https://github.com/ashleymills/Reachability.swift/tree/develop /var/folders/6w/fl6bb2fs2kdfbfxd2hz0cjr40000gn/T/d20150714-3515-kn5q7m --single-branch --depth 1

Cloning into '/var/folders/6w/fl6bb2fs2kdfbfxd2hz0cjr40000gn/T/d20150714-3515-kn5q7m'...

fatal: repository 'https://github.com/ashleymills/Reachability.swift/tree/develop/' not found

**Comment by UncleRic** [comment]
Via Unix prompt:

$~/workarea/testarea:git clone https://github.com/ashleymills/Reachability.swift/tree/develop
Cloning into 'develop'...
fatal: repository 'https://github.com/ashleymills/Reachability.swift/tree/develop/' not found
$~/workarea/testarea:

**Comment by ashleymills** [comment]
Develop now merged into master - closing issue
