### ISSUE TITLE
Github releases outdated

### ISSUE THREAD

**Issue by Drusy** [ashleymills/Reachability.swift#283]
Your framework is super popular, the work on the code is great but the release page on Github has been abandonned since december 2015. 

https://github.com/ashleymills/Reachability.swift/releases

> Version 2.3.3
> ashleymills released this on 11 Dec 2015

As a Carthage user, I wish you publish clearly every production ready release so we grab really quickly the latest tag.
I am opening this issue because I accidently pointed `~> 2.3` in my Cartfile and haven't seen the small `Since on 10 Oct 2017  Show 5 newer tags`

**Comment by ashleymills** [comment]
Apologies - this is now being updated as of 4.2.0

Cheers
Ash
