### ISSUE TITLE
Plaform condition appears to be testing for simulator environment; use 'targetEnvironment(simulator)' instead

### ISSUE THREAD

**Issue by ekmobile** [ashleymills/Reachability.swift#285]
Since the Xcode 9.3 Update this morning there is a warning in version 4.1.0:

"Reachability.swift:136:42: Plaform condition appears to be testing for simulator environment; use 'targetEnvironment(simulator)' instead"

targetEnvironment(simulator) seems to be working in a first test.

**Comment by DanielStormApps** [comment]
Submitted PR #284 to resolve this. 👍

**Comment by jordanhbuiltbyhq** [comment]
Will you be updating the CocoaPod version soon? I continue to see this warning but have the latest release installed, 4.1.0.

**Comment by artofthetrek** [comment]
@jordanhbuiltbyhq Checking the README file, note that 

> If you're adding Reachability.swift using CocoaPods, note that the framework name has changed from ReachabilitySwift to Reachability (for consistency with Carthage)

Changing from ReachabilitySwift to Reachability in your Podfile and running `pod install` again fixes this warning.

**Comment by bbaic** [comment]
this fix breaks things in xcode 9.2.

See issue #309
