### ISSUE TITLE
Failable initializer cannot fail?

### ISSUE THREAD

**Issue by TeunVR** [ashleymills/Reachability.swift#29]
In the 2.0-beta branch the initializer is failable.
Is that really necessary? It never seems to fail in the code?

**Comment by TeunVR** [comment]
Oops, nevermind

**Comment by ashleymills** [comment]
In the **develop** branch, I've clarified which init methods are failable, made the class methods "throws" along with `startNotifier()` and updated the README. Would be great if people could check this out and test it!
Thanks
Ash
