### ISSUE TITLE
isReachable() doesn't work

### ISSUE THREAD

**Issue by mmilnePSG** [ashleymills/Reachability.swift#3]
The timer works, but because there can be a delay of up to 5 seconds I do a manual check using isReachable() when the user tries to access the net in my app.  However isReachable() will return TRUE even if I have just turned off WIFI.  Does isReachable() do an instant check of connectivity or does it only give a correct result after the timer fires?

**Comment by ashleymills** [comment]
Hi @mmilnePSG 

Is this a problem on an actual device, or in the simulator?

**Comment by ashleymills** [comment]
Closed as duplicate of #2
