### ISSUE TITLE
[4.2] Reachability()?.connection returns .none right after been initialized

### ISSUE THREAD

**Issue by Drusy** [ashleymills/Reachability.swift#307]
In 4.1, the following code `Reachability().connection` would provide `.wifi` or `.cellular`.
Since 4.2,  `Reachability().connection` returns `.none` right after the initialization. 

After a while, if subscribing to the notifications, the value returns to the real reachability state.
Is this the designed behavior or is this a regression  ?

Regards

**Comment by ashleymills** [comment]
@Drusy That looks like a regression. Thanks for reporting, I'll take a look

Cheers
Ash

**Comment by Drusy** [comment]
@ashleymills my sample is as simple as this

```
let reachability = Reachability()
print(reachability!.connection)
// No Connection
```

I am not calling `startNotifier()` because in that case I do not need the notifications. I may misuse your API, but the behavior is definitely changing between 4.1 and 4.2

**Comment by ashleymills** [comment]
OK, I see the problem. I'll push a fix later today.

**Comment by ashleymills** [comment]
https://github.com/ashleymills/Reachability.swift/releases/tag/v4.2.1 released
