### ISSUE TITLE
4.2.1 version is broken: callbacks not called

### ISSUE THREAD

**Issue by alexnivanov** [ashleymills/Reachability.swift#312]
I upgraded pod from 4.1.0 to 4.2.1 and it got broken:
*whenReachable* is not getting called :(

I downgraded back to 4.1.0 and it works fine!

Tested on iPhone 7, iOS 11.4.1

p.s. I did clean build both times.

**Comment by ashleymills** [comment]
Have you tried running the example project? Does the same thing happen?

**Comment by alexnivanov** [comment]
@ashleymills can you please advise on how to run it?
I cloned the repo, opened Reachability.xcodeproj, but it seems like a library, don't get how to run an app...

**Comment by ashleymills** [comment]
You need to build  and run the **ReachabilitySample** target

**Comment by alexnivanov** [comment]
I have ReachabilitySample target, but it is not selectable for running:
http://prntscr.com/kubrva

Sorry, I'm not experienced in Xcode.
