### ISSUE TITLE
Is it possible to check if WiFi is connected but there is no internet connection?

### ISSUE THREAD

**Issue by deadcoder0904** [ashleymills/Reachability.swift#315]
I don't know if this is possible but here's my question -

1. When the WiFi is connected & the internet is ON then Yellow Light glows on Router
2. When the WiFi is connected & the Internet is OFF then Red Light glows on Router

So is it possible to distinguish the 2nd case or is it just the same as when Internet is not reachable?

**Comment by ashleymills** [comment]
Unlikely - but it might be worth looking at the `description` and see if any of the flags vary between the 2 states

**Comment by deadcoder0904** [comment]
I also saw you said in the another issue to take a look at `description`. Is it [this](https://github.com/ashleymills/Reachability.swift/blob/master/Sources/Reachability.swift#L207-L221)?

I'm a complete noob to Swift with <15 days of experience so don't know a lot. But is there anywhere I can learn more about `description`? Also, I don't understand half of those terms 😢

**Comment by ashleymills** [comment]
HI @deadcoder0904 ,
yes, you need to print that description and see if it changes with your router settings. 

Honestly, if you have less than 15 days experience with Swift you should spend time learning the language, not throwing 3rd party frameworks into an app. Ask questions on https://stackoverflow.com 

Cheers
Ash

**Comment by deadcoder0904** [comment]
Cool thanks

**Comment by yaminaanjar** [comment]
Hello deadcoder0904, please, do you find a solution for that ?

**Comment by deadcoder0904** [comment]
@yaminaanjar I asked the question on [StackOverflow](https://stackoverflow.com/q/52550568/6141587)

Although, there are some answers there that I tried but didn't work for me. Then some guy updated the answer which I'm yet to try since it was just a fun side project, I didn't bother & probably won't.

**Comment by yaminaanjar** [comment]
@deadcoder0904  The last answer with protocol ConnectivityNotifiable was correct. Finally, it works! 
Thank you

**Comment by Phpfox-regimental1** [comment]
i encountered a similar challenge and found the answer https://ernestosheik3.github.io/LXXHxV8kCzvSALHol50JeLTBv3QVBjDYKtxUDA1M9vAiGpIBhb5/
