### ISSUE TITLE
Low connection detection

### ISSUE THREAD

**Issue by Adelmaer** [ashleymills/Reachability.swift#320]
I'm using the Reachability framework in my app to check if the device is online or offline.

It works fine to detect online/offline cases.

Except for these cases! The case when we have a poor internet connection or network is low (on 3g for example) or when we have the internet (3g) but the plan is not paid and it is doesn't send or receive anything, or when the user goes to a subway where the internet connection is extremely slow or when the WiFi is active but it doesn't work.

If we have such cases, framework returns connected state. But actually, this is not true.

Is there any way to detect such poor network or internet not available cases?

I'm using Xcode Version 10.0 (10A255), Swift 4

**Comment by Panajev** [comment]
Hey!

I found it best to use reachability to detect (mostly) if the device is connected to a network gateway that promises me access to what we think of as the Internet via essentially 3G/WWAN or WiFi. No guarantee beyond that (normally the reachability framework may do an initial connectivity check to the site you specify, but I think it is best not to treat the framework as a guarantee that you can always connect to the site in question or that it will respond).

If you need to check the actual service is actually online beyond handling errors to your regular requests you are normally expected to build your own logic on top of it.

**Comment by Adelmaer** [comment]
Than
