### ISSUE TITLE
Not showing Correct on Ethernet

### ISSUE THREAD

**Issue by anonymouz4** [ashleymills/Reachability.swift#322]
It says on WiFI even though I'm connected via Ethernet

**Comment by anonymouz4** [comment]
@ashleymills Why close? Was it already fixed?

**Comment by ashleymills** [comment]
It was closed because you couldn’t be bothered to give me any more info than “it’s not working”

**Comment by anonymouz4** [comment]
Well there wasn't much more Info I could give. When the reachability changes or when getting the current status, it returns `reachableViaWiFi`, even though I'm on ethernet

**Comment by ashleymills** [comment]
https://github.com/ashleymills/Reachability.swift/blob/master/CONTRIBUTING.md

Raising an issue here

Has someone else raised the issue?

Check through currently open AND closed issues. If the issue has already been raised, please comment on the existing one.

It doesn't work

"It doesn't work" doesn't help anyone solve your problem. What doesn't work?

It didn't compile?
It crashed?
It didn't show the correct Reachability state?
It won't compile

If it won't compile, what error messages are you seeing? Include the code that's at fault - a screen shot might help here.

It crashed

If it crashed, include a stack-trace, and the code that's in error.

Other stuff

What version of Reachability.Swift are you using?
How is it installed? Manually, CocoaPods, Carthage?
Does it occur on device or simulator? Which device?
What OS version are you running on?
How often does it happen?
Are there steps you can take to reproduce it?
Help me to help you! Ash
