### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by lvandal** [ashleymills/Reachability.swift#325]
Xcode 10.2 Beta now comes with Swift 5. Any plans on updating Reachability to support it? Thanks!

**Comment by ashleymills** [comment]
Yes, I’ll create a Swift 5 branch

Ashley Mills
T: +44 7976 363 943 
E: ashleymills@mac.com 
W: http://joylordsystems.com

**Comment by ViniciusScorsatto** [comment]
Hi guys, any update on that? Thanks a lot

**Comment by dglancy** [comment]
Swift 5 support out today. I am noticing some warnings in /master branch.

Any thoughts?

[https://imgur.com/a/1vflDlA](https://imgur.com/a/1vflDlA)

**Comment by ashleymills** [comment]
Done!
