### ISSUE TITLE
Detect connection state through the "connection" property

### ISSUE THREAD

**Issue by lmsmartins** [ashleymills/Reachability.swift#333]
Hi,

When directly accessing the "connection" property within a Reachability instance, do I need to start the notifier? I've seen in the examples how to detect the connection state either through closures or notifications, but I'm not quite sure on how the "connection" property works. Does a reachability instance update its "connection" property through its own notifications? Does it automatically start an "inner" notifier?

Currently, I'm instantiating a Reachability instance in the AppDelegate and then directly querying its "connection" property whenever I need to check the connection status. Does this make sense?

Thanks!

**Comment by bleroux-orange** [comment]
If the notifier is not started, Reachability does not update its status. 
So, if you do't want to start the notifier, you need to instantiate a new Reachability instance each time you want to read the current status.

**Comment by lmsmartins** [comment]
That does make sense. Thank you!
