### ISSUE TITLE
Unable to use Reachability with Swift 5

### ISSUE THREAD

**Issue by jdhindsa** [ashleymills/Reachability.swift#334]
I'm getting the following error when I try to use Reachability with Swift 5

Showing Recent Messages
:-1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'ReachabilitySwift')

**Comment by ashleymills** [comment]
Either upgrade to Xcode 10.2 or specify a previous release of Reachability.swift in your podfile
