### ISSUE TITLE
Enum case 'wifi' is not a member of type 'Reachability.Connection?'

### ISSUE THREAD

**Issue by CRoig** [ashleymills/Reachability.swift#335]
I am using the README example to identify the connectivity status. However, I am getting a compilation error on the following snippet:

```
switch reachability?.connection {
     case Reachability.Connection.none:
           //Do Stuff
     case Reachability.Connection.wifi:
           //Do Stuff
     case Reachability.Connection.cellular:
          //Do Stuff
    @unknown default:
}
```

> Enum case 'wifi' is not a member of type 'Reachability.Connection?'

Same for none and cellular

**Comment by ashleymills** [comment]
Which Xcode / iOS / Swift / Reachability?

**Comment by ashleymills** [comment]
You're switching on an optional. Either unwrap `if let connection = reachability?.connection` or use `case Reachability.Connection.wifi?` etc
