### ISSUE TITLE
develop branch readme out of date

### ISSUE THREAD

**Issue by cmyr** [ashleymills/Reachability.swift#34]
nitpicky: The documentation on the develop branch does not reflect that the `init` methods are now failable, and return optionals.

**Comment by ashleymills** [comment]
If you could raise a pull request to fix, that would be great!
Cheers
Ash

**Comment by Ji11erBug** [comment]
Why is it failable? How to reproduce it? Can i unwrap it?

**Comment by ashleymills** [comment]
@Ji11erBug What have you tried?

**Comment by ashleymills** [comment]
In the *develop* branch, I've clarified which init methods are failable, made the class methods "throws" along with startNotifier() and updated the README
