### ISSUE TITLE
Carthage: failed with exit code 1

### ISSUE THREAD

**Issue by guidupas** [ashleymills/Reachability.swift#340]
I am trying to get the framework using Carthage:

This is my Cartfile:

`github "ashleymills/Reachability.swift"`

and I am receiving this error message:

> A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/ashleymills/Reachability.swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /var/root/Library/Caches/org.carthage.CarthageKit/dependencies/Reachability.swift)) failed with exit code 1

I am using Carhage 0.33.0 and Swift 5

Thanks in advance.

**Comment by nikGayko** [comment]
The same thing

**Comment by cliss** [comment]
+1 on Carthage `0.33.0` and Xcode 11b4.

**Comment by cliss** [comment]
# Short short version

`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

# Long version

Looking at this further, I think I [somewhat] understand the problem.

The error message spells it out:

```
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/ashleymills/Reachability.swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/casey/Library/Caches/org.carthage.CarthageKit/dependencies/Reachability.swift)) failed with exit code 1
```

I ran the command that seems to have failed sparately:

```bash-3.2$ /usr/bin/env git fetch --prune --quiet https://github.com/ashleymills/Reachability.swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*
```

And got the following error message:

`warning: no common commits`

That made me think that there's some sort of cache mismatch between Carthage and what's on Github. Looking again at the original error message, I noted this:

`(launched in /Users/casey/Library/Caches/org.carthage.CarthageKit/dependencies/Reachability.swift)`

So I did the following:

`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

And that seems to have fixed my problem.

**Comment by loganblevins** [comment]
🎉

**Comment by fllaryora** [comment]
Thank you Casey Liss
