### ISSUE TITLE
Compile Issue Reachability 4.3.1 built with Carthage - .unavailable not recognized

### ISSUE THREAD

**Issue by thejeff77** [ashleymills/Reachability.swift#346]
Hello, I just installed the framework with Carthage - it pulled down version 4.3.1, built it with an error. The build error occurs on the line from the documentation:

`case .unavailable:`

With compile error:

> Pattern cannot match values of type 'Reachability.Connection'

The compiler doesn't have an issue with any of the other Connection types (.none, .wifi, .cellular), as it builds if I put these three in the case statement - it only chokes on .unavailable.

<img width="873" alt="Screen Shot 2019-07-21 at 4 23 24 PM" src="https://user-images.githubusercontent.com/8584457/61597985-74a68f80-abd4-11e9-93e4-80f9685c21f9.png">

I have a mixed Swift (5.0) and objective C project and have used other carthage libraries in it. 

Here is the class I attempted to build in case it helps - 

```

import Foundation
import Reachability

@objc class ConnectionUtil : NSObject {
    
    @objc public static let sharedInstance = ConnectionUtil()
    
    let reachability = Reachability()!
    
    override init() {
        super.init()
        
        NotificationCenter.default.addObserver(self, selector: #selector(reachabilityChanged(note:)), name: .reachabilityChanged, object: reachability)
        do{
            try reachability.startNotifier()
        }catch{
            print("could not start reachability notifier")
        }
    }
    
    deinit {
        reachability.stopNotifier()
        NotificationCenter.default.removeObserver(self, name: .reachabilityChanged, object: reachability)
    }
    
    @objc func reachabilityChanged(note: Notification) {
        
        let reachability = note.object as! Reachability
        
        let connection = reachability.connection
        
        switch reachability.connection {
        case .wifi:
            print("Reachable via WiFi")
        case .cellular:
            print("Reachable via Cellular")
        case .unavailable:
            print("Network not reachable")
        }
//        case .none:
//            print("Not Reachable")
//        }
    }
}

```

**Comment by stof** [comment]
`.unavailable` is part of the 5.0 changes. In 4.3.1, that was `.none`

**Comment by thejeff77** [comment]
It works for me now.
