### ISSUE TITLE
Swift 2.0 errors

### ISSUE THREAD

**Issue by wangchao92** [ashleymills/Reachability.swift#35]
<img width="260" alt="screen shot 2015-08-19 at 1 43 43 pm" src="https://cloud.githubusercontent.com/assets/5442025/9349416/674ec46c-4678-11e5-8b5a-652b819f696c.png">
<img width="926" alt="screen shot 2015-08-19 at 1 43 52 pm" src="https://cloud.githubusercontent.com/assets/5442025/9349418/69f4ab6e-4678-11e5-8c6e-db7370ecf4dd.png">

**Comment by ashleymills** [comment]
This issue was fixed by #33

**Comment by wangchao92** [comment]
Thanks!
So I should use " pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift', :tag => '2.0-beta5' " ?

**Comment by ashleymills** [comment]
There's a problem validating the pod spec for 2.0-beta5 at the moment. 
See http://stackoverflow.com/questions/32098766/podspec-lint-failing-with-latest-xcode-beta

**Comment by wangchao92** [comment]
I used it and v2.0-beta5 was installed successfully.
