### ISSUE TITLE
No Reachability notification when switching Wifi back on with simulator

### ISSUE THREAD

**Issue by ciathyza** [ashleymills/Reachability.swift#350]
Test reachability on iOS simulator ...

Turn Wifi off: App receives a reachability unavailable notification.
Turn Wifi back on: App doesn't receive any reachability notification.

Is this a known issue?

**Comment by williamhqs** [comment]
Same issue here +1

**Comment by olgadanylova** [comment]
+ 1 on simulator, fix please

**Comment by ashleymills** [comment]
@olgadanylova This is an open source project - you are welcome to contribute a fix yourself.

**Comment by ashleymills** [comment]
Duplicates #317
