### ISSUE TITLE
Update Cocoapods Support

### ISSUE THREAD

**Issue by LowAmmo** [ashleymills/Reachability.swift#379]
Just seeing that v. 5.1.0 is tagged - but the cocoapod spec repo hasn't been updated with this new version.

Also, getting a build warning about:

     The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.

(seeing this building with Xcode 12.4 - I believe we saw the warning with earlier versions, too)

Thinking that can be resolved by just specifying a platform in the podspec - 

     s.platform = :ios, '13.0'

Thanks!

**Comment by anees17861** [comment]
Any update on this? It still shows 5.0.0 as the highest version in cocoapods

**Comment by LowAmmo** [comment]
@ashleymills - just bumping to see if someone could update the cocoapods version?

**Comment by dianakarh** [comment]
@ashleymills - I'm getting this error when trying to push my library to Cocoapods
`- NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'ReachabilitySwift' from project 'Pods')`
Could you please bump the target to 11?
