### ISSUE TITLE
Reachability NotificationObserver not called when Network change iOS 14.5 Xcode 12.5

### ISSUE THREAD

**Issue by gharary** [ashleymills/Reachability.swift#380]
I have installed Reachability using SPM, Xcode 12.5 beta 2, Project in SwiftUI

What version of Reachability.Swift are you using? 5.1.0
How is it installed? Manually, CocoaPods, Carthage? SPM
Does it occur on a device or simulator? Which device? Both, iPhone 8 (iOS 14.5 beta), Simulator
What OS version are you running on? 14.5

The code is quite simple, I call reachability in AppDelegate and it starts fine but won't get called when the network changes.
I even have enabled "Access WiFi Information" but no result.

Not in a real device (iPhone 8, iOS 14.5), nor in Simulator

<img width="1280" alt="Screen Shot 2021-02-27 at 12 33 53 PM" src="https://user-images.githubusercontent.com/16289125/109382841-0f5e6880-78f8-11eb-82eb-30bc40a195ac.png">

**Comment by elincoln** [comment]
Your `Reachability` instance deallocates immediately after that method exits -- you need to retain a reference to it somewhere.

**Comment by gharary** [comment]
Thanks!

**Comment by vinamelody** [comment]
Hi @gharary how did you solve this?
