### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kenroyandfamily** [ashleymills/Reachability.swift#4]
Add Reachability.swift to my project and tried both closure code and notification code, but it does not work.   Test project doesn't work either.

**Comment by kenroyandfamily** [comment]
Oops, looks like it was just me :-)  Works fine.

**Comment by ashleymills** [comment]
Glad you got it working! If you've used Reachability.swift in a project in the App Store, please let me know and I'll give it a shout out on the home page.
