### ISSUE TITLE
Make version 5.2.0 available in Cocoapods

### ISSUE THREAD

**Issue by ammu2288** [ashleymills/Reachability.swift#403]
Hello @ashleymills, can you please make version 5.2.0 available in Cocoapods. This will help us deploy this with the new Privacy Manifest changes.

**Comment by JING202303** [comment]
Hello, @ashleymills, need make version 5.2.0 available in Cocoapods.
ReachabilitySwift.podspec has error?
- s.version      = '5.0.0'

**Comment by charmipatalia** [comment]
Any update on this? I am facing one issue in latest xcode 15 if I use 5.0.0 version

**Comment by codingiran** [comment]
should push lastest spec to cocopods

**Comment by ashleymills** [comment]
5.2.1 has been pushed to trunk, you can test this with `pod trunk info ReachabilitySwift`
```
ReachabilitySwift
    - Versions:
      - 1.1 (2015-05-05 10:17:59 UTC)
      - 2.0 (2015-09-18 08:29:39 UTC)
      - 2.0-beta1 (2015-06-15 09:25:20 UTC)
      - 2.1 (2015-10-20 10:52:00 UTC)
      - 2.3 (2015-11-16 13:41:08 UTC)
      - 2.3.3 (2015-12-11 12:30:58 UTC)
      - 2.4 (2016-09-15 18:23:54 UTC)
      - 3 (2016-09-15 08:06:08 UTC)
      - 4.0.0 (2017-10-10 15:53:07 UTC)
      - 4.0-beta2 (2017-09-19 09:54:06 UTC)
      - 4.1.0 (2017-10-10 16:12:38 UTC)
      - 4.2.0 (2018-08-29 11:03:36 UTC)
      - 4.2.1 (2018-08-30 13:32:02 UTC)
      - 4.3.0 (2018-10-02 12:19:40 UTC)
      - 4.3.1 (2019-03-28 10:04:42 UTC)
      - 5.0.0 (2019-10-15 14:10:45 UTC)
      - 5.0.0-beta1 (2019-06-19 20:22:50 UTC)
      - 5.2.1 (2024-03-16 12:35:25 UTC)
```

but for this hasn't been reflected in the specs repo… CocoaPods/Specs

Any idea how to resolve this?

**Comment by ashleymills** [comment]
@codingiran this should be done now
