### ISSUE TITLE
Incorrect project in .podspec related to new Privacy Manifest requirement

### ISSUE THREAD

**Issue by SethBaldwin** [ashleymills/Reachability.swift#408]
https://github.com/ashleymills/Reachability.swift/blob/c01127cb51f591045696128effe43c16840d08bf/ReachabilitySwift.podspec#L21

Wondering if this should be ` s.resource_bundles = {"ReachabilitySwift" => ["Sources/PrivacyInfo.xcprivacy"]}`?

@tommyming

**Comment by tommyming** [comment]
@SethBaldwin thanks for finding this out! 

Yes, you are correct, I mainly work on SPM at that PM, so I haven't checked on the cocoapods side thoroughly, sorry for that. 
Maybe you can create a PR real quick for the maintainer to merge? 

Please also double-check if there are any mistakes made by me on `Package.swift`.
Seems the maintainer doesn't have the time to do code review.

Thanks again!

**Comment by SethBaldwin** [comment]
I'm just noticing there is already a PR open for this change...
https://github.com/ashleymills/Reachability.swift/pull/402
