### ISSUE TITLE
License disproportionately restrictive

### ISSUE THREAD

**Issue by levous** [ashleymills/Reachability.swift#41]
I was curious if you meant to include such a restrictive license?  Considering the fact that this is a port of a port from Apple, I'd expect a very unrestrictive license (MIT, Apache).  I truly appreciate the work you put into it and am very grateful that you shared it.  The license requirements make it something that has to be checked by legal and, therefore, quite expensive (of course, none of that cost goes to you, sadly).

Would you consider a more liberal license?  I'd much rather contribute back to this project with any future fixes that might come along and I'd bet that others share my sentiment.

**Comment by gkaimakas** [comment]
The licence mentioned in the podspec is MIT. Just checked it

**Comment by ashleymills** [comment]
@levous what made you think the licence was something other than MIT?

**Comment by ashleymills** [comment]
No reply so closing issue
