### ISSUE TITLE
Error reported by privacy report generation related to privacy manifest key

### ISSUE THREAD

**Issue by kirandwarkan** [ashleymills/Reachability.swift#410]
I archived my app in Xcode and generated a privacy report from the organizer window. The resulting PDF has an "Errors Encountered" section expressing missing an expected key `NSPrivacyCollectedDataTypes` even though it is present in the manifest.

![Screenshot 2024-03-20 at 3 57 54 PM](https://github.com/ashleymills/Reachability.swift/assets/5456543/849b5044-f52e-4751-8426-086989f31497)

I am importing Reachability 5.2.0 via SPM

**Comment by wailfirdaous** [comment]
<img width="812" alt="Screenshot 2024-04-11 at 12 34 58" src="https://github.com/ashleymills/Reachability.swift/assets/48024183/04cdf4b1-6adb-4d72-aa40-207bc7be5c7a">

Same for me can you please fix it?

**Comment by adzerjitchii** [comment]
Hi @ashleymills any news on NSPrivacyCollectedDataTypes fix ?

**Comment by emans** [comment]
Good afternoon, I have the same question any estimated time to get this fixed? Thanks for the help

**Comment by ashleymills** [comment]
Anyone here is welcome to raise a PR to fix

Cheers
Ash

**Comment by ashleymills** [comment]
@adzerjitchii Thanks for the PR. It's merged and a new release 5.2.2 created
