### ISSUE TITLE
Fix privacy manifest

### ISSUE THREAD

**Issue by catarinapeixoto** [ashleymills/Reachability.swift#418]
Uploading a new App version to App Store Connect brings the following error: "TMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “ReachabilitySwift.bundle/PrivacyInfo.xcprivacy”."

**Comment by milhous** [comment]
+1

**Comment by rsonawne** [comment]
+1

**Comment by javier2409** [comment]
+1
A similar issue has been fixed recently in #410 but now apple says the manifest is invalid when uploading an app bundle to the app store


>ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “ReachabilitySwift.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

**Comment by ashleymills** [comment]
Thanks for raising - please feel free to submit a pull request that fixes the issue and I'll create a new release

**Comment by catarinapeixoto** [comment]
> Thanks for raising - please feel free to submit a pull request that fixes the issue and I'll create a new release

https://github.com/ashleymills/Reachability.swift/pull/419

**Comment by YOrange834** [comment]
+1

**Comment by nataliakozlovska** [comment]
+1

**Comment by omkar-indee** [comment]
Is there any update on this, we have lot of apps and all of them are affected with this

**Comment by belousovgm** [comment]
+1

**Comment by ashleymills** [comment]
Hopefully #420 Should have resolved this issue
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  ReachabilitySwift (5.2.4) successfully published
 📅  October 3rd, 13:26
 🌎  https://cocoapods.org/pods/ReachabilitySwift
 👍  Tell your friends!
--------------------------------------------------------------------------------
```
