### ISSUE TITLE
swift2.0 support

### ISSUE THREAD

**Issue by longxianlin** [ashleymills/Reachability.swift#43]
errors many

**Comment by longxianlin** [comment]
http://stackoverflow.com/questions/30743408/check-for-internet-conncetion-in-swift-2-ios-9

**Comment by ashleymills** [comment]
I'm not sure what your problem is.

The develop branch has been merged into master so the project now fully supports Swift 2.0. Please make sure you are using the latest version of Xcode.

Ash

**Comment by y25zhao** [comment]
I got many compile errors as well. I think the latest version is not backward compatible. For those who are not using Swift 2.0, the latest version won't work.

**Comment by ashleymills** [comment]
For Swift 1.2 support, checkout release *v1.1*, hash 5c62387
