### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by sleekuser** [ashleymills/Reachability.swift#45]

**Comment by ashleymills** [comment]
Carthage isn't currently on my roadmap for this project. It's just a single file that can be dropped into a project - even Cocoapods seems like overkill.

**Comment by sleekuser** [comment]
@ashleymills First of all, thanks for this awesome port for swift. I think `Cocoapods` is an overkill for swift projects. I am having crashing issues with `Cocoapods` and I have moved to Carthage. I agree that just for a single file a framework will be too much, but having a support will be awesome. I have forked your project and already added carthage support here: [sleekuser/Reachability.swift](https://github.com/sleekuser/Reachability.swift)

**Comment by apocolipse** [comment]
+1 for carthage support
It may seem like overkill but its /MUCH/ cleaner than either a: cocoapods or b: git submodules for keeping up with changes.

Thanks @sleekuser for the fork :)

**Comment by uny** [comment]
+1
I would like [sleekuser/Reachability.swift](https://github.com/sleekuser/Reachability.swift) to be pull requested for this repository.

**Comment by Danappelxx** [comment]
I really like the framework, but I'm confused about your reasoning for not adding Carthage support - the _only_ thing you need to do is create a framework target and share the scheme. Carthage is much simpler than Cocoapods, so it doesn't make sense that you would say Carthage is out of scope, but Cocoapods isn't.

**Comment by tomco** [comment]
+1 for Carthage support

**Comment by ashleymills** [comment]
I've merged pull request #55 into the develop branch - https://github.com/ashleymills/Reachability.swift/tree/develop

Please checkout, test and raise any issues in that #55's comment thread.

Cheers
Ash

**Comment by ashleymills** [comment]
This feature has been merged into the main branch
