### ISSUE TITLE
<SCNetworkReachability>, <SCNetworkReachabilityFlags> and many more errors

### ISSUE THREAD

**Issue by Luissoo** [ashleymills/Reachability.swift#46]
HI,

I just added ReachabilitySwift in my Podfile to my project running in Xcode6.4/Swift1.2.
And at the first compilation i got 20 errors on the Reachability.swift file, i don't understand why ?

<img width="347" alt="capture d ecran 2015-09-29 a 13 27 46" src="https://cloud.githubusercontent.com/assets/5419579/10162786/f18fc626-66ad-11e5-9a77-41d53aba7d08.png">

Thanks a lot !

**Comment by ashleymills** [comment]
The current release of Reachability.Swift is Swift 2.0 compatible. Your choice is either…

1) Move to Xcode 7 and Swift 2.0
2) Checkout and use an older release of Reachability.Swift. Release 1.1 should work for you… https://github.com/ashleymills/Reachability.swift/releases/tag/v1.1

Cheers
Ash

Ashley Mills
T: +44 7976 363 943 
E: ashleymills@mac.com 
W: http://joylordsystems.com

**Comment by Luissoo** [comment]
Great it works thank you
