### ISSUE TITLE
can not use the library with carthage

### ISSUE THREAD

**Issue by gedaiu** [ashleymills/Reachability.swift#47]
*** Skipped building Reachability.swift due to the error:
Dependency "Reachability.swift" has no shared framework schemes

**Comment by ashleymills** [comment]
See https://github.com/ashleymills/Reachability.swift/issues/45

**Comment by ashleymills** [comment]
I've merged pull request #55 into the develop branch - https://github.com/ashleymills/Reachability.swift/tree/develop

Please checkout, test and raise any issues in that #55's comment thread.

Cheers
Ash
