### ISSUE TITLE
Failable inits / throws

### ISSUE THREAD

**Issue by ashleymills** [ashleymills/Reachability.swift#48]
In the **develop** branch, I've clarified which init methods are failable, made the class methods "throws" along with `startNotifier()` and updated the README. Would be great if people could check this out and make sure I haven't made a mess of it!

Thanks
Ash

**Comment by martinr448** [comment]
The throwing class methods cannot return `nil`, so their return type should be `Reachability` instead of `Reachability?`.

I would consider making `public convenience init?(hostname: String)` a throwing class method as well.

**Comment by ashleymills** [comment]
@martinr448 thank you. Are you the same MartinR on SO by any chance?

**Comment by ashleymills** [comment]
Branch has been merged into master
