### ISSUE TITLE
about bugs:  0xA9FE0000  

### ISSUE THREAD

**Issue by WinEIM** [ashleymills/Reachability.swift#5]
about bugs:  0xA9FE0000  
xcode will show this error: Integer literal overflows when stored into 'Int'

fixed in this way: 

change row 102  

        localWifiAddress.sin_addr.s_addr = in_addr_t(Int64(0xA9FE0000).bigEndian)

to:
        var iDef: __uint32_t = 0xA9FE0000
        localWifiAddress.sin_addr.s_addr = in_addr_t(iDef)

**Comment by timkettering** [comment]
I encountered this same problem when running the simulator for iPhone 4s.  This may be a 32-bit processor issue.  The workaround described above fixes it.

**Comment by alo12** [comment]
I have the same issue as well.  The solution from @WinEIM also worked for me.

**Comment by ashleymills** [comment]
Thanks all for the heads up. I've just pushed a change that should resolve this issue.
