### ISSUE TITLE
Check on app startup if internet available.

### ISSUE THREAD

**Issue by reshadf** [ashleymills/Reachability.swift#52]
Hello sir,

I managed to create a very nice functionality in my app when the network status changes. But somehow I can't check for this when the app starts up. Is there a nice way to do this in AppDelegate? it looks like this right now. 

     let reachability = Reachability.reachabilityForInternetConnection()

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: "reachabilityChanged:",
            name: ReachabilityChangedNotification,
            object: reachability)
            reachability?.startNotifier()
    }

**Comment by slecoustre** [comment]
+1

**Comment by ottersoftware** [comment]
You could just call reachability.isReachable to check the status.

**Comment by Danappelxx** [comment]
@ottersoftware he wants to be (programmatically) notified if the status changes - it wouldn't make sense to constantly check `reachability.isReachable`.

**Comment by ashleymills** [comment]
I’ve just checked in an update on the develop branch, that automatically performs a reachability check on starting the notifier. Hopefully this should resolve your issue. Please check this out, test it and post any feedback here.

Cheers
Ash

**Comment by ashleymills** [comment]
This has now been checked int the master branch - Release v2.3
