### ISSUE TITLE
WatchOS 2.0

### ISSUE THREAD

**Issue by berlos** [ashleymills/Reachability.swift#57]
Hi,

When I try to add ReachabilitySwift via cocoapods on my project I get this error:

(watchOS 2.0) is not compatible with `ReachabilitySwift (2.1)`, which does not support `watchos`

Podfile : 
target 'MyApp Extension' do
    
    platform :watchos, '2.0'
    
    pod 'ReachabilitySwift', '~> 2.1'
    
end

do you know how to fix it ?

Best Regards

**Comment by ashleymills** [comment]
The only supported platforms are `ios` and `osx`.

 **Reachability.swift** is designed to let the app know whether the device has a cellular or wifi connection to the internet - but this doesn't apply to a a watch app.

What exactly are you trying to achieve here?
