### ISSUE TITLE
Add watchOS and tvos to podspec

### ISSUE THREAD

**Issue by evermeer** [ashleymills/Reachability.swift#61]
ReachabilitySwift should be able to support watchOS and TVOS.
Just add these lines to the .podspec:

s.watchos.deployment_target = '2.0'
s.tvos.deployment_target = '9.0'

**Comment by ashleymills** [comment]
The only supported platforms are ios and osx.

Reachability.swift is designed to let the app know whether the device has a cellular or wifi connection to the internet. This certainly doesn't apply to a watch app… and in any case watchOS 2.0 doesn't support the `SystemConfiguration` framework.

tvOS does support `SystemConfiguration`, so technically that would work. But the Apple TV unit is never connected to the internet via a cellular connection, so there would probably need to be some update to the code to exclude that case.

It's not just as simple as updating the podspec I'm afraid.

What exactly are you trying to achieve here?

**Comment by evermeer** [comment]
Reachability is a dependency in a cocoapod library of mine that will have support for Apple TV and Watch OS. See https://github.com/evermeer/EVURLCache
It's a generic URLCache  class that should be able to run on both Apple TV and Apple Watch. When I add ReachabilitySwift as a dependency I get the error that it does not support these so that my library is also not allowed to support these.

**Comment by ashleymills** [comment]
As I mentioned previously, watchOS 2.0 doesn't support the `SystemConfiguration` framework, so there's no way to use the `SCNetworkReachability…` methods that Reachability.swift uses. So for watchOS it's a non-starter. You can confirm this for yourself by manually including the Reachability.swift file into your project.

For tvOS it looks more promising, although it needs some investigation - I have a new Apple TV  so I'll see what's required. Or more than happy to take a pull request!

For your Cocoapod, certainly as far as watchOS is concerned, it looks like you need some kind of conditional include of pods. I don't know enough about Cocoapods to know if this is supported… but there is an issue here that might help - https://github.com/CocoaPods/CocoaPods/issues/731

Cheers
Ash

**Comment by ashleymills** [comment]
tvOS is supported from v2.3.3
