### ISSUE TITLE
Carthage installation problem

### ISSUE THREAD

**Issue by LiborZ** [ashleymills/Reachability.swift#62]
I still have problem with adding Reachability via Carthage. I get this error:

    Dependency "Reachability.swift" has no shared framework schemes for any of the platforms: iOS

I've updated brew and other things. Where could be problem? Thanks

**Comment by ashleymills** [comment]
I think this might be due to me not tagging and creating a new release - so you may have been picking up v2.1 which didn't support Carthage.

I've now added Release 2.2 - please try it out and post any feedback here

Cheers
Ash

**Comment by LiborZ** [comment]
And now it's working. Thanks for help and thanks for this library :+1:

**Comment by ashleymills** [comment]
Great! Glad you're finding it useful :smile: 

Cheers
Ash
