### ISSUE TITLE
App Crashing in Production Mode

### ISSUE THREAD

**Issue by srijan-kumar-bs** [ashleymills/Reachability.swift#66]
- [ ] App crashing in Adhoc .ipa file after using Swift 1.1 code and Reachability.swift code. Its working fine in Development of app through Xcode but .ipa created resulting crashing.

**Comment by ashleymills** [comment]
Maybe there is a problem in your code

**Comment by srijan-kumar-bs** [comment]
Yes Got It. Thanks.
