### ISSUE TITLE
TV OS compatibility

### ISSUE THREAD

**Issue by sts2055** [ashleymills/Reachability.swift#67]
Hi there,

Is the code compatible with TV OS? If yes, would it be possible to update the podspec and push it to cocoapods' spec repo?

If you don't have time, please let me know and I can create a pull request and/or (with your permission) push the new spec to the main spec repo.

**Comment by ashleymills** [comment]
Hi, 

please have a read of issue #61 and if you'd like to create a pull request, please go ahead!

Many thanks
Ash

**Comment by sts2055** [comment]
Hi, I created the pull request.
It contains an apple sample project. 
I pretty much didn't have to change anything. Worked out of the box.
The podspec has its version incremented to 2.3.3 and the tvos dependency added.
I linted it on my side and it passed

**Comment by sts2055** [comment]
@ashleymills If you don't have time, would you be ok if I push the new spec from my fork? (the git source would be pointing to my fork, since only my fork contains the 2.3.3 tag)

**Comment by ashleymills** [comment]
Many thanks for this PR - it's really appreciated.

I've merged the PR and pushed the podspec to trunk, can you please check that all is OK?

Cheers … and Happy Christmas
Ash

**Comment by sts2055** [comment]
Using the new podspec, tested it on the simulator -- works like a charm 🤘
