### ISSUE TITLE
Reachability Crashes within iPhone 5 (v8.3) Simulation

### ISSUE THREAD

**Issue by UncleRic** [ashleymills/Reachability.swift#7]
Environment: Xcode 6.3
File: Reachability.swift, line #102....

I get the following compile crash within iPhone 5 simulation:
"Integer literal overflows when stored into 'Int':
 // IN_LINKLOCALNETNUM is defined in <netinet/in.h> as! 169.254.0.0
        localWifiAddress.sin_addr.s_addr = in_addr_t(Int(0xA9FE0000).bigEndian)

The compiler points to '0xA9FE000' as the source of the error.

Note: this doesn't occur within IPhone 6 simulation.

**Comment by j4nos** [comment]
Same for me, problem on this line on device:

localWifiAddress.sin_addr.s_addr = in_addr_t(Int64(0xA9FE0000).bigEndian)

**Comment by ashleymills** [comment]
Please try the latest version of the code, and let me know if it's been resolved.

**Comment by j4nos** [comment]
thanks, works, I am appreciative :)
