### ISSUE TITLE
在连接WIFI的情况下检测

### ISSUE THREAD

**Issue by ai930** [ashleymills/Reachability.swift#72]
在连接WIFI的情况，且用户所连接的WIFI是局域网而非广域网。服务器连接超时等检测没有好的解决方案吗？

**Comment by ashleymills** [comment]
Sorry - I can only respond to issues in English.

**Comment by ai930** [comment]
In the case of connection WIFI, and the user is connected to WIFI LAN rather than WAN. Server connection timeouts and other testing is no good solution?
