### ISSUE TITLE
Network Lost

### ISSUE THREAD

**Issue by balkrishanyadav** [ashleymills/Reachability.swift#83]
If any service is running and  lock device in this period then network lost message is coming. 
Thanks,

**Comment by ashleymills** [comment]
You won't be able to get reachability updates in iOS when the app isn't opened, and you can only keep the app running in the background for a limited time to complete long running tasks, or for certain other limited applications.

See the following Apple doc about background execution: https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html
