### ISSUE TITLE
Reachability detecting cellular network (not cellular data)?

### ISSUE THREAD

**Issue by erolsk8** [ashleymills/Reachability.swift#84]
Can Reachability be used to detect if device is connected to any cellular network, so not if it has cellular data, but if it's _connected to carrier_?

I just want to detect when there is **No Service** message in top left instead of carrier name.

Thank you

**Comment by ashleymills** [comment]
Reachability currently only detects either:

no connection
cellular connection
wifi connection 

The *No service* message will appear when `isReachableViaWWAN() == false`

**Comment by kinza88** [comment]
Hey! Does this class work for 4g as well? 
I found recommendations to it, but from few comments on posts, seems like it doesn't support 4g. Is it so? Waiting for your reply. 

@ashleymills

**Comment by ashleymills** [comment]
@kinza88 Reachability checks for WiFi and Cellular connectivity - that's 3G, 4G, 5G(?) etc. Anyone who comments otherwise doesn't know what they're talking about.
