### ISSUE TITLE
Not getting change in state

### ISSUE THREAD

**Issue by edolecki** [ashleymills/Reachability.swift#85]
I set up for iOS. I set up closures and also notification (just in case). I get connected state just fine. 

When I go to the settings on the iOS device (not simulator) and turn Wi-Fi off, I get no notification (using print("<state>")) of the change from closure or notification. 

    'func beginReachability() {
        let reachability:Reachability
        do {
            reachability = try Reachability.reachabilityForInternetConnection()
        } catch {
            print("unable to create Reachability")
            return
        }

        reachability.whenReachable = { reachability in
            dispatch_async(dispatch_get_main_queue()) {
                if reachability.isReachableViaWiFi() {
                    print("\nWI-FI")
                } else {
                    print("\nReachable via Cellular")
                }
            }
        }
        
        reachability.whenUnreachable = { reachability in
            dispatch_async(dispatch_get_main_queue()) {
                print("\nNot reachable")
            }
        }
        
        //This is set up correctly (function) - never is received
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: "reachabilityChanged:",
            name: ReachabilityChangedNotification,
            object: reachability)
        
        do {
            try reachability.startNotifier()
        } catch {
            print(error)
        }
    }'

I put the notification code on the main queue too...

`func reachabilityChanged(note: NSNotification){
let reachability = note.object as! Reachability

dispatch_async(dispatch_get_main_queue()) {
    if reachability.isReachable() {...`

**Comment by macteo** [comment]
It seems that the readme is misleading.
You should remove the 

    let reachability:Reachability

and add it as as instance variable so it will be retained (move the declaration outside the `func` scope)

    var reachability : Reachability?

then change the following calls of `reachability` to `reachability?` inside your implementation.

**Comment by abunur** [comment]
@macteo 's solution solves this issue.  I'll submit a pull request on the read me.

**Comment by edolecki** [comment]
Thank you - it does indeed work and makes sense.
