### ISSUE TITLE
Reachability in background 

### ISSUE THREAD

**Issue by leo-one** [ashleymills/Reachability.swift#86]
My app need to execute a code every time the connection is changed to available, even the app is not opened or it is in background.
In Android, we can solve it easily by Broadcast Receiver / Intent Filter.

I am trying to do the same in iOS / Swift with the code below:

```Swift
var reachability:Reachability!;

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions:  ....
{
    // code
    do {
            reachability = try Reachability.reachabilityForInternetConnection()
            
            NSNotificationCenter.defaultCenter().addObserver(self,
                selector: "reachabilityChanged:", name: ReachabilityChangedNotification,
                object: reachability)
  
            try reachability.startNotifier()
        } catch {
            print("Unable to create Reachability")
        }
}

func reachabilityChanged(note: NSNotification) {
        
        let reachability = note.object as! Reachability
        
        if reachability.isReachable() {
            if reachability.isReachableViaWiFi() {
                print("Reachable via WiFi")
            } else {
                print("Reachable via Cellular")
            }
        } else {
            print("Not reachable")
        }
}
```
But after the app is close, the reachability function keeps on during some seconds then it does not notice anymore the connection changes.

What's the best approach in this case ?

**Comment by ashleymills** [comment]
You won't be able to get reachability updates in iOS when the app isn't opened, and you can only keep the app running in the background for a limited time to complete long running tasks, or for certain other limited applications.

See the following Apple doc about background execution: https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html
