### ISSUE TITLE
Not getting changes in state

### ISSUE THREAD

**Issue by DesmondPang** [ashleymills/Reachability.swift#93]
The reachabilityChanged() only called once when it start. There is no notification and call reachabilityChanged when change state. 

 var reachability:Reachability?
        
        do {
            reachability = try Reachability.reachabilityForInternetConnection()
            NSNotificationCenter.defaultCenter().addObserver(self,selector: "reachabilityChanged:",name: ReachabilityChangedNotification,object: reachability)
            try reachability?.startNotifier()
        } catch {
            print("Unable to create Reachability")
        }

    func reachabilityChanged(note: NSNotification) {
        
        let reachability = note.object as! Reachability
        
        if reachability.isReachable() {
            if reachability.isReachableViaWiFi() {
                print("Reachable via WiFi")
            } else {
                print("Reachable via Cellular")
            }
        } else {
            print("Not reachable")
        }
    }

**Comment by ashleymills** [comment]
Where is `var reachability:Reachability?` declared? You need to have a strong reference to it.

**Comment by DesmondPang** [comment]
OMG, I placed it in viewDidLoad(). Now I change to a strong reference. It works. Thank you so much.
